/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superrolbattle;

import instancias.CampoDeBatalla;
import instancias.Token;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import java.util.concurrent.RecursiveAction;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import recursos.CargaBase;
import recursos.Recursos;
import static recursos.Recursos.verTabla;
import superrolbattle.ventanas.*;

/**
 *
 * @author Juan
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jLabel_uso_ao.setVisible(false);
        campo = new CampoDeBatalla();

        Principal.ventana = this;

        for (Iterator iterator = Recursos.soldados.iterator(); iterator.hasNext();) {
            Token next = (Token) iterator.next();
            JPanelFormToken jpft = new JPanelFormToken(next);

            jPanel_Pnj.add(jpft);
            JPanelFormToken_Accion jjpfta = new JPanelFormToken_Accion(next, this, 0);
            jPanel_sinAcciones_tokens.add(jjpfta);
            campo.agregarTokens(jjpfta);
        }
        //jPanel_Pnj.setLayout(new GridLayout(jPanel_Pnj.getComponentCount()/4+1, 4, 2, 2));
        jPanel_sinAcciones_tokens.setLayout(new GridLayout(1, jPanel_sinAcciones_tokens.getComponentCount(), 2, 2));
        /* tablei = new MyTable(true);
        tabled = new MyTable(false);
        modeloTI = (MyTableModel) tablei.getModel();
        modeloTD = (MyTableModel) tabled.getModel();

        tablei.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Token tok = (Token) modeloTI.getValueAt(tablei.getSelectedRow(), 0);
                jTextField_NV.setText("" + tok.getNivel());
                jTextField_BO.setText("" + tok.getHabilidades().getBo());
                jTextField_BD.setText("" + tok.getHabilidades().getBd());
                jTextField_Arm.setText("" + tok.getHabilidades().getArmadura());
                jLabel_bi.setText(tok.getManoIZQ().getArmaEquipada().toString());
                jLabel_bd.setText(tok.getManoDER().getArmaEquipada().toString());
            }
        });
        tabled.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Token tok = (Token) modeloTD.getValueAt(tabled.getSelectedRow(), 0);
                jTextField_NV.setText("" + tok.getNivel());
                jTextField_BO.setText("" + tok.getHabilidades().getBo());
                jTextField_BD.setText("" + tok.getHabilidades().getBd());
                jTextField_Arm.setText("" + tok.getHabilidades().getArmadura());
                jLabel_bi.setText(tok.getManoIZQ().getArmaEquipada().toString());
                jLabel_bd.setText(tok.getManoDER().getArmaEquipada().toString());
            }
        });

        tablei.setAutoCreateRowSorter(true);
        tabled.setAutoCreateRowSorter(true);
        
        
        jScrollPane1.add(tablei);
        this.jScrollPane1.setViewportView(tablei);
        jPanel2.add(tabled);
        this.jScrollPane2.setViewportView(tabled);
         */
        this.repaint();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel_General = new javax.swing.JPanel();
        jPanel_Acciones = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton_crear = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton_crear_pj = new javax.swing.JButton();
        jLabel_uso_ao = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_asalto = new javax.swing.JTextField();
        jButton_definir = new javax.swing.JButton();
        jButton_comenzar = new javax.swing.JButton();
        jButton_terminar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Campo_tab = new javax.swing.JPanel();
        scrollPane2 = new java.awt.ScrollPane();
        jPanel_Pjs = new javax.swing.JPanel();
        scrollPane1 = new java.awt.ScrollPane();
        jPanel_Pnj = new javax.swing.JPanel();
        jPanel_Asaltos_tab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel_Aslatos = new javax.swing.JPanel();
        jPanel_SinAcciones = new javax.swing.JPanel();
        jPanel_Titulo_SinAcciones = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel_SinAcciones_panel = new java.awt.ScrollPane();
        jPanel_sinAcciones_tokens = new javax.swing.JPanel();
        jPanel_CargaSortilegios = new javax.swing.JPanel();
        jPanel_Titulo_cargaSortilegios = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton_avanzarFaseAsalto1 = new javax.swing.JButton();
        jPanel_campo_CargaSortilegios = new javax.swing.JPanel();
        jPanel_RealizaSortilegios = new javax.swing.JPanel();
        jPanel_Titulo_RealizaSortilegios = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton_avanzarFaseAsalto2 = new javax.swing.JButton();
        jPanel_RealizaSortilegios_campo = new javax.swing.JPanel();
        jPanel_LanzaProyectiles = new javax.swing.JPanel();
        jPanel_Titulo_DisparaProyectiles = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton_avanzarFaseAsalto3 = new javax.swing.JButton();
        jPanel_LanzaProyectiles_campo = new javax.swing.JPanel();
        jPanel_CargaProyectiles = new javax.swing.JPanel();
        jPanel_Titulo_cargaProyectiles = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton_avanzarFaseAsalto4 = new javax.swing.JButton();
        jPanel_CargaProyectiles_campo = new javax.swing.JPanel();
        jPanel_PararProyectiles = new javax.swing.JPanel();
        jPanel_Titulo_PararProyectiles = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton_avanzarFaseAsalto5 = new javax.swing.JButton();
        jPanel_PararProyectiles_campo = new javax.swing.JPanel();
        jPanel_movimientoYmaniobra = new javax.swing.JPanel();
        jPanel_Titulo_movimientoYmaniobra = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton_avanzarFaseAsalto6 = new javax.swing.JButton();
        jPanel_movimientoYmaniobra_campo = new javax.swing.JPanel();
        jPanel_AtaqueCuerpoaCuerpo = new javax.swing.JPanel();
        jPanel_Titulo_AtaqueCuerpoaCuerpo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton_avanzarFaseAsalto7 = new javax.swing.JButton();
        jPanel_AtaqueCuerpoaCuerpo_campo = new javax.swing.JPanel();
        jPanel_Movimiento = new javax.swing.JPanel();
        jPanel_Titulo_Movimiento = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton_avanzarFaseAsalto8 = new javax.swing.JButton();
        jPanel_Movimiento_campo = new javax.swing.JPanel();
        jPanel_MovimientoEstatico = new javax.swing.JPanel();
        jPanel_Titulo_MovimientoEstatico = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton_avanzarFaseAsalto9 = new javax.swing.JButton();
        jPanel_MovimientoEstatic_campo = new javax.swing.JPanel();
        jPanel_Resumen_tab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multiple Battle Simulator");
        setMaximumSize(new java.awt.Dimension(1024, 860));

        jPanel_General.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_General.setAutoscrolls(true);
        jPanel_General.setMaximumSize(new java.awt.Dimension(720, 410));
        jPanel_General.setLayout(new java.awt.BorderLayout());

        jPanel_Acciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Acciones.setPreferredSize(new java.awt.Dimension(396, 54));
        jPanel_Acciones.setLayout(new javax.swing.BoxLayout(jPanel_Acciones, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setMaximumSize(new java.awt.Dimension(100007, 50));
        jPanel7.setMinimumSize(new java.awt.Dimension(300, 0));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jButton_crear.setText("Crear");
        jButton_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_crearActionPerformed(evt);
            }
        });
        jPanel7.add(jButton_crear);

        jButton2.setText("FIGHT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        jButton1.setText("Agregar Enemigo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        jButton_crear_pj.setText("Agregar Pj");
        jButton_crear_pj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_crear_pjMouseClicked(evt);
            }
        });
        jButton_crear_pj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_crear_pjActionPerformed(evt);
            }
        });
        jPanel7.add(jButton_crear_pj);

        jLabel_uso_ao.setText("     Usar Shift + click para accion de oportunidad");
        jPanel7.add(jLabel_uso_ao);

        jPanel_Acciones.add(jPanel7);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Nùmero de Asalto");
        jPanel2.add(jLabel2);

        jTextField_asalto.setEditable(false);
        jTextField_asalto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_asalto.setText("0");
        jTextField_asalto.setMaximumSize(new java.awt.Dimension(25, 25));
        jPanel2.add(jTextField_asalto);

        jButton_definir.setText("Definir Acciones");
        jButton_definir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_definirActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_definir);

        jButton_comenzar.setText("Comenzar Asalto");
        jButton_comenzar.setEnabled(false);
        jButton_comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_comenzarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_comenzar);

        jButton_terminar.setText("Terminar Asalto");
        jButton_terminar.setEnabled(false);
        jButton_terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_terminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_terminar);

        jPanel_Acciones.add(jPanel2);

        jPanel_General.add(jPanel_Acciones, java.awt.BorderLayout.PAGE_START);

        jPanel_Campo_tab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Campo_tab.setAutoscrolls(true);
        jPanel_Campo_tab.setLayout(new java.awt.BorderLayout());

        jPanel_Pjs.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 1));
        scrollPane2.add(jPanel_Pjs);

        jPanel_Campo_tab.add(scrollPane2, java.awt.BorderLayout.NORTH);

        jPanel_Pnj.setAutoscrolls(true);
        jPanel_Pnj.setPreferredSize(new java.awt.Dimension(253, 324));
        jPanel_Pnj.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 1));
        scrollPane1.add(jPanel_Pnj);

        jPanel_Campo_tab.add(scrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Campo", jPanel_Campo_tab);

        jPanel_Asaltos_tab.setLayout(new javax.swing.BoxLayout(jPanel_Asaltos_tab, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_Aslatos.setLayout(new javax.swing.BoxLayout(jPanel_Aslatos, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_SinAcciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_SinAcciones.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel_SinAcciones.setRequestFocusEnabled(false);
        jPanel_SinAcciones.setLayout(new javax.swing.BoxLayout(jPanel_SinAcciones, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_Titulo_SinAcciones.setBackground(new java.awt.Color(255, 204, 204));
        jPanel_Titulo_SinAcciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Titulo_SinAcciones.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel_Titulo_SinAcciones.setPreferredSize(new java.awt.Dimension(549, 30));
        jPanel_Titulo_SinAcciones.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel11.setBackground(new java.awt.Color(255, 153, 153));
        jLabel11.setText("Sin Acciones");
        jPanel_Titulo_SinAcciones.add(jLabel11, java.awt.BorderLayout.CENTER);

        jPanel_SinAcciones.add(jPanel_Titulo_SinAcciones);

        jPanel_sinAcciones_tokens.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 1));
        jPanel_SinAcciones_panel.add(jPanel_sinAcciones_tokens);

        jPanel_SinAcciones.add(jPanel_SinAcciones_panel);

        jPanel_Aslatos.add(jPanel_SinAcciones);

        jPanel_CargaSortilegios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_CargaSortilegios.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel_CargaSortilegios.setRequestFocusEnabled(false);
        jPanel_CargaSortilegios.setLayout(new javax.swing.BoxLayout(jPanel_CargaSortilegios, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_Titulo_cargaSortilegios.setBackground(new java.awt.Color(204, 204, 255));
        jPanel_Titulo_cargaSortilegios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Titulo_cargaSortilegios.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel_Titulo_cargaSortilegios.setPreferredSize(new java.awt.Dimension(549, 30));
        jPanel_Titulo_cargaSortilegios.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel3.setText("Carga de Sortilegios");
        jPanel_Titulo_cargaSortilegios.add(jLabel3, java.awt.BorderLayout.WEST);

        jButton_avanzarFaseAsalto1.setText("Siguiente");
        jButton_avanzarFaseAsalto1.setEnabled(false);
        jButton_avanzarFaseAsalto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_avanzarFaseAsalto1ActionPerformed(evt);
            }
        });
        jPanel_Titulo_cargaSortilegios.add(jButton_avanzarFaseAsalto1, java.awt.BorderLayout.LINE_END);

        jPanel_CargaSortilegios.add(jPanel_Titulo_cargaSortilegios);

        jPanel_campo_CargaSortilegios.setMinimumSize(new java.awt.Dimension(2, 70));
        jPanel_campo_CargaSortilegios.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));
        jPanel_CargaSortilegios.add(jPanel_campo_CargaSortilegios);

        jPanel_Aslatos.add(jPanel_CargaSortilegios);

        jPanel_RealizaSortilegios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_RealizaSortilegios.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel_RealizaSortilegios.setRequestFocusEnabled(false);
        jPanel_RealizaSortilegios.setLayout(new javax.swing.BoxLayout(jPanel_RealizaSortilegios, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_Titulo_RealizaSortilegios.setBackground(new java.awt.Color(204, 204, 255));
        jPanel_Titulo_RealizaSortilegios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Titulo_RealizaSortilegios.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel_Titulo_RealizaSortilegios.setPreferredSize(new java.awt.Dimension(549, 30));
        jPanel_Titulo_RealizaSortilegios.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel4.setText("Realizacion de Sortilegios");
        jPanel_Titulo_RealizaSortilegios.add(jLabel4, java.awt.BorderLayout.WEST);

        jButton_avanzarFaseAsalto2.setText("Siguiente");
        jButton_avanzarFaseAsalto2.setEnabled(false);
        jButton_avanzarFaseAsalto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_avanzarFaseAsalto2ActionPerformed(evt);
            }
        });
        jPanel_Titulo_RealizaSortilegios.add(jButton_avanzarFaseAsalto2, java.awt.BorderLayout.LINE_END);

        jPanel_RealizaSortilegios.add(jPanel_Titulo_RealizaSortilegios);

        jPanel_RealizaSortilegios_campo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));
        jPanel_RealizaSortilegios.add(jPanel_RealizaSortilegios_campo);

        jPanel_Aslatos.add(jPanel_RealizaSortilegios);

        jPanel_LanzaProyectiles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_LanzaProyectiles.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel_LanzaProyectiles.setRequestFocusEnabled(false);
        jPanel_LanzaProyectiles.setLayout(new javax.swing.BoxLayout(jPanel_LanzaProyectiles, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_Titulo_DisparaProyectiles.setBackground(new java.awt.Color(204, 204, 255));
        jPanel_Titulo_DisparaProyectiles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Titulo_DisparaProyectiles.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel_Titulo_DisparaProyectiles.setPreferredSize(new java.awt.Dimension(549, 30));
        jPanel_Titulo_DisparaProyectiles.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel6.setText("Disparo de Proyectiles");
        jPanel_Titulo_DisparaProyectiles.add(jLabel6, java.awt.BorderLayout.WEST);

        jButton_avanzarFaseAsalto3.setText("Siguiente");
        jButton_avanzarFaseAsalto3.setEnabled(false);
        jButton_avanzarFaseAsalto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_avanzarFaseAsalto3ActionPerformed(evt);
            }
        });
        jPanel_Titulo_DisparaProyectiles.add(jButton_avanzarFaseAsalto3, java.awt.BorderLayout.LINE_END);

        jPanel_LanzaProyectiles.add(jPanel_Titulo_DisparaProyectiles);

        jPanel_LanzaProyectiles_campo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));
        jPanel_LanzaProyectiles.add(jPanel_LanzaProyectiles_campo);

        jPanel_Aslatos.add(jPanel_LanzaProyectiles);

        jPanel_CargaProyectiles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_CargaProyectiles.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel_CargaProyectiles.setRequestFocusEnabled(false);
        jPanel_CargaProyectiles.setLayout(new javax.swing.BoxLayout(jPanel_CargaProyectiles, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_Titulo_cargaProyectiles.setBackground(new java.awt.Color(204, 204, 255));
        jPanel_Titulo_cargaProyectiles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Titulo_cargaProyectiles.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel_Titulo_cargaProyectiles.setPreferredSize(new java.awt.Dimension(549, 30));
        jPanel_Titulo_cargaProyectiles.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel5.setText("Carga de Proyectiles");
        jPanel_Titulo_cargaProyectiles.add(jLabel5, java.awt.BorderLayout.WEST);

        jButton_avanzarFaseAsalto4.setText("Siguiente");
        jButton_avanzarFaseAsalto4.setEnabled(false);
        jButton_avanzarFaseAsalto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_avanzarFaseAsalto4ActionPerformed(evt);
            }
        });
        jPanel_Titulo_cargaProyectiles.add(jButton_avanzarFaseAsalto4, java.awt.BorderLayout.LINE_END);

        jPanel_CargaProyectiles.add(jPanel_Titulo_cargaProyectiles);

        jPanel_CargaProyectiles_campo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));
        jPanel_CargaProyectiles.add(jPanel_CargaProyectiles_campo);

        jPanel_Aslatos.add(jPanel_CargaProyectiles);

        jPanel_PararProyectiles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_PararProyectiles.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel_PararProyectiles.setRequestFocusEnabled(false);
        jPanel_PararProyectiles.setLayout(new javax.swing.BoxLayout(jPanel_PararProyectiles, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_Titulo_PararProyectiles.setBackground(new java.awt.Color(204, 204, 255));
        jPanel_Titulo_PararProyectiles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Titulo_PararProyectiles.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel_Titulo_PararProyectiles.setPreferredSize(new java.awt.Dimension(549, 30));
        jPanel_Titulo_PararProyectiles.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel12.setText("Parar Proyectiles");
        jPanel_Titulo_PararProyectiles.add(jLabel12, java.awt.BorderLayout.WEST);

        jButton_avanzarFaseAsalto5.setText("Siguiente");
        jButton_avanzarFaseAsalto5.setEnabled(false);
        jButton_avanzarFaseAsalto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_avanzarFaseAsalto5ActionPerformed(evt);
            }
        });
        jPanel_Titulo_PararProyectiles.add(jButton_avanzarFaseAsalto5, java.awt.BorderLayout.LINE_END);

        jPanel_PararProyectiles.add(jPanel_Titulo_PararProyectiles);

        jPanel_PararProyectiles_campo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));
        jPanel_PararProyectiles.add(jPanel_PararProyectiles_campo);

        jPanel_Aslatos.add(jPanel_PararProyectiles);

        jPanel_movimientoYmaniobra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_movimientoYmaniobra.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel_movimientoYmaniobra.setRequestFocusEnabled(false);
        jPanel_movimientoYmaniobra.setLayout(new javax.swing.BoxLayout(jPanel_movimientoYmaniobra, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_Titulo_movimientoYmaniobra.setBackground(new java.awt.Color(204, 204, 255));
        jPanel_Titulo_movimientoYmaniobra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Titulo_movimientoYmaniobra.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel_Titulo_movimientoYmaniobra.setPreferredSize(new java.awt.Dimension(549, 30));
        jPanel_Titulo_movimientoYmaniobra.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel7.setText("Movimiento y Maniobra");
        jPanel_Titulo_movimientoYmaniobra.add(jLabel7, java.awt.BorderLayout.WEST);

        jButton_avanzarFaseAsalto6.setText("Siguiente");
        jButton_avanzarFaseAsalto6.setEnabled(false);
        jButton_avanzarFaseAsalto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_avanzarFaseAsalto6ActionPerformed(evt);
            }
        });
        jPanel_Titulo_movimientoYmaniobra.add(jButton_avanzarFaseAsalto6, java.awt.BorderLayout.LINE_END);

        jPanel_movimientoYmaniobra.add(jPanel_Titulo_movimientoYmaniobra);

        jPanel_movimientoYmaniobra_campo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));
        jPanel_movimientoYmaniobra.add(jPanel_movimientoYmaniobra_campo);

        jPanel_Aslatos.add(jPanel_movimientoYmaniobra);

        jPanel_AtaqueCuerpoaCuerpo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_AtaqueCuerpoaCuerpo.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel_AtaqueCuerpoaCuerpo.setRequestFocusEnabled(false);
        jPanel_AtaqueCuerpoaCuerpo.setLayout(new javax.swing.BoxLayout(jPanel_AtaqueCuerpoaCuerpo, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_Titulo_AtaqueCuerpoaCuerpo.setBackground(new java.awt.Color(204, 204, 255));
        jPanel_Titulo_AtaqueCuerpoaCuerpo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Titulo_AtaqueCuerpoaCuerpo.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel_Titulo_AtaqueCuerpoaCuerpo.setPreferredSize(new java.awt.Dimension(549, 30));
        jPanel_Titulo_AtaqueCuerpoaCuerpo.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel8.setText("Ataques Cuerpo a Cuerpo");
        jPanel_Titulo_AtaqueCuerpoaCuerpo.add(jLabel8, java.awt.BorderLayout.WEST);

        jButton_avanzarFaseAsalto7.setText("Siguiente");
        jButton_avanzarFaseAsalto7.setEnabled(false);
        jButton_avanzarFaseAsalto7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_avanzarFaseAsalto7ActionPerformed(evt);
            }
        });
        jPanel_Titulo_AtaqueCuerpoaCuerpo.add(jButton_avanzarFaseAsalto7, java.awt.BorderLayout.LINE_END);

        jPanel_AtaqueCuerpoaCuerpo.add(jPanel_Titulo_AtaqueCuerpoaCuerpo);

        jPanel_AtaqueCuerpoaCuerpo_campo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));
        jPanel_AtaqueCuerpoaCuerpo.add(jPanel_AtaqueCuerpoaCuerpo_campo);

        jPanel_Aslatos.add(jPanel_AtaqueCuerpoaCuerpo);

        jPanel_Movimiento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Movimiento.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel_Movimiento.setRequestFocusEnabled(false);
        jPanel_Movimiento.setLayout(new javax.swing.BoxLayout(jPanel_Movimiento, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_Titulo_Movimiento.setBackground(new java.awt.Color(204, 204, 255));
        jPanel_Titulo_Movimiento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Titulo_Movimiento.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel_Titulo_Movimiento.setPreferredSize(new java.awt.Dimension(549, 30));
        jPanel_Titulo_Movimiento.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel9.setText("Desplazamiento");
        jPanel_Titulo_Movimiento.add(jLabel9, java.awt.BorderLayout.WEST);

        jButton_avanzarFaseAsalto8.setText("Siguiente");
        jButton_avanzarFaseAsalto8.setEnabled(false);
        jButton_avanzarFaseAsalto8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_avanzarFaseAsalto8ActionPerformed(evt);
            }
        });
        jPanel_Titulo_Movimiento.add(jButton_avanzarFaseAsalto8, java.awt.BorderLayout.LINE_END);

        jPanel_Movimiento.add(jPanel_Titulo_Movimiento);

        jPanel_Movimiento_campo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));
        jPanel_Movimiento.add(jPanel_Movimiento_campo);

        jPanel_Aslatos.add(jPanel_Movimiento);

        jPanel_MovimientoEstatico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_MovimientoEstatico.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel_MovimientoEstatico.setRequestFocusEnabled(false);
        jPanel_MovimientoEstatico.setLayout(new javax.swing.BoxLayout(jPanel_MovimientoEstatico, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_Titulo_MovimientoEstatico.setBackground(new java.awt.Color(204, 204, 255));
        jPanel_Titulo_MovimientoEstatico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Titulo_MovimientoEstatico.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel_Titulo_MovimientoEstatico.setPreferredSize(new java.awt.Dimension(549, 30));
        jPanel_Titulo_MovimientoEstatico.setLayout(new java.awt.BorderLayout(20, 0));

        jLabel10.setText("Movimiento Estàtico");
        jPanel_Titulo_MovimientoEstatico.add(jLabel10, java.awt.BorderLayout.WEST);

        jButton_avanzarFaseAsalto9.setText("Siguiente");
        jButton_avanzarFaseAsalto9.setEnabled(false);
        jButton_avanzarFaseAsalto9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_avanzarFaseAsalto9ActionPerformed(evt);
            }
        });
        jPanel_Titulo_MovimientoEstatico.add(jButton_avanzarFaseAsalto9, java.awt.BorderLayout.LINE_END);

        jPanel_MovimientoEstatico.add(jPanel_Titulo_MovimientoEstatico);

        jPanel_MovimientoEstatic_campo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));
        jPanel_MovimientoEstatico.add(jPanel_MovimientoEstatic_campo);

        jPanel_Aslatos.add(jPanel_MovimientoEstatico);

        jScrollPane2.setViewportView(jPanel_Aslatos);

        jPanel_Asaltos_tab.add(jScrollPane2);

        jTabbedPane1.addTab("Asalto", jPanel_Asaltos_tab);

        jPanel_Resumen_tab.setLayout(new java.awt.BorderLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel_Resumen_tab.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Resumen", jPanel_Resumen_tab);

        jPanel_General.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel_General, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("salir");
        jMenuItem3.setName("jMISalir"); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenuItem3.getAccessibleContext().setAccessibleDescription("");

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jCheckBoxMenuItem1.setText("Atacar al mismo Lado");
        jCheckBoxMenuItem1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxMenuItem1StateChanged(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Ayuda");

        jCheckBoxMenuItem2.setText("Imprimir por Consola");
        jCheckBoxMenuItem2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxMenuItem2ItemStateChanged(evt);
            }
        });
        jMenu5.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_crearActionPerformed

        Object[] ObjTk = CrearToken.nuevoToken();
        boolean lado = (boolean) ObjTk[0];
        Token tk = (Token) ObjTk[1];
        Recursos.soldados.add(tk);

    }//GEN-LAST:event_jButton_crearActionPerformed

    private void jCheckBoxMenuItem1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1StateChanged
        Principal.dosLados = jCheckBoxMenuItem1.isSelected();
    }//GEN-LAST:event_jCheckBoxMenuItem1StateChanged

    private void jCheckBoxMenuItem2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ItemStateChanged
        Recursos.imprimirPorConsola = jCheckBoxMenuItem2.isSelected();
    }//GEN-LAST:event_jCheckBoxMenuItem2ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (campo.puedenComenzarlosAtaques()) {
            //CampoDeBatalla.resolverAsalto();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Object[] ObjTk = CrearToken.nuevoToken();
        Token tk = (Token) ObjTk[1];
        Recursos.soldados.add(tk);
        JPanelFormToken jpft = new JPanelFormToken(tk);
        jPanel_Pnj.add(jpft);
        this.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton_crear_pjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_crear_pjMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_crear_pjMouseClicked

    private void jButton_crear_pjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_crear_pjActionPerformed

        Object[] ObjTk = CrearToken.nuevoToken();
        Token tk = (Token) ObjTk[1];
        Recursos.soldados.add(tk);

        JPanelFormToken jpft = new JPanelFormToken(tk);
        jPanel_Pjs.add(jpft);

        jpft.setVisible(true);
        this.repaint();

    }//GEN-LAST:event_jButton_crear_pjActionPerformed

    private void jButton_comenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_comenzarActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        avanzarButtonFase(BUTTONFASE_DESARROLLO);
    }//GEN-LAST:event_jButton_comenzarActionPerformed

    private void jButton_definirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_definirActionPerformed
        avanzarButtonFase(BUTTONFASE_DEFINICION);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton_definirActionPerformed

    private void jButton_terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_terminarActionPerformed
        avanzarButtonFase(BUTTONFASE_RESULTADOS);
    }//GEN-LAST:event_jButton_terminarActionPerformed

    private void jButton_avanzarFaseAsalto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_avanzarFaseAsalto1ActionPerformed
        JPanel jp = (JPanel) jButton_avanzarFaseAsalto1.getParent().getParent().getComponent(1);
        if (todosActuaron(jp)) {
            avanzarFaseDeAsalto(-1);
        } else {
            JOptionPane.showMessageDialog(this, "Aún hay personajes sin actuar");
        }
    }//GEN-LAST:event_jButton_avanzarFaseAsalto1ActionPerformed

    private void jButton_avanzarFaseAsalto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_avanzarFaseAsalto2ActionPerformed
        JPanel jp = (JPanel) jButton_avanzarFaseAsalto2.getParent().getParent().getComponent(1);
        if (todosActuaron(jp)) {
            avanzarFaseDeAsalto(-1);
        } else {
            JOptionPane.showMessageDialog(this, "Aún hay personajes sin actuar");
        }
    }//GEN-LAST:event_jButton_avanzarFaseAsalto2ActionPerformed

    private void jButton_avanzarFaseAsalto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_avanzarFaseAsalto3ActionPerformed
        JPanel jp = (JPanel) jButton_avanzarFaseAsalto3.getParent().getParent().getComponent(1);
        if (todosActuaron(jp)) {
            avanzarFaseDeAsalto(-1);
        } else {
            JOptionPane.showMessageDialog(this, "Aún hay personajes sin actuar");
        }
    }//GEN-LAST:event_jButton_avanzarFaseAsalto3ActionPerformed

    private void jButton_avanzarFaseAsalto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_avanzarFaseAsalto4ActionPerformed
        JPanel jp = (JPanel) jButton_avanzarFaseAsalto4.getParent().getParent().getComponent(1);
        if (todosActuaron(jp)) {
            avanzarFaseDeAsalto(-1);
        } else {
            JOptionPane.showMessageDialog(this, "Aún hay personajes sin actuar");
        }
    }//GEN-LAST:event_jButton_avanzarFaseAsalto4ActionPerformed

    private void jButton_avanzarFaseAsalto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_avanzarFaseAsalto5ActionPerformed
        JPanel jp = (JPanel) jButton_avanzarFaseAsalto5.getParent().getParent().getComponent(1);
        if (todosActuaron(jp)) {
            avanzarFaseDeAsalto(-1);
        } else {
            JOptionPane.showMessageDialog(this, "Aún hay personajes sin actuar");
        }
    }//GEN-LAST:event_jButton_avanzarFaseAsalto5ActionPerformed

    private void jButton_avanzarFaseAsalto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_avanzarFaseAsalto6ActionPerformed
        JPanel jp = (JPanel) jButton_avanzarFaseAsalto6.getParent().getParent().getComponent(1);
        if (todosActuaron(jp)) {
            avanzarFaseDeAsalto(-1);
        } else {
            JOptionPane.showMessageDialog(this, "Aún hay personajes sin actuar");
        }
    }//GEN-LAST:event_jButton_avanzarFaseAsalto6ActionPerformed

    private void jButton_avanzarFaseAsalto7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_avanzarFaseAsalto7ActionPerformed
        JPanel jp = (JPanel) jButton_avanzarFaseAsalto7.getParent().getParent().getComponent(1);
        if (todosActuaron(jp)) {
            avanzarFaseDeAsalto(-1);
        } else {
            JOptionPane.showMessageDialog(this, "Aún hay personajes sin actuar");
        }
    }//GEN-LAST:event_jButton_avanzarFaseAsalto7ActionPerformed

    private void jButton_avanzarFaseAsalto8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_avanzarFaseAsalto8ActionPerformed
        JPanel jp = (JPanel) jButton_avanzarFaseAsalto8.getParent().getParent().getComponent(1);
        if (todosActuaron(jp)) {
            avanzarFaseDeAsalto(-1);
        } else {
            JOptionPane.showMessageDialog(this, "Aún hay personajes sin actuar");
        }
    }//GEN-LAST:event_jButton_avanzarFaseAsalto8ActionPerformed

    private void jButton_avanzarFaseAsalto9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_avanzarFaseAsalto9ActionPerformed
        JPanel jp = (JPanel) jButton_avanzarFaseAsalto9.getParent().getParent().getComponent(1);
        if (todosActuaron(jp)) {
            avanzarFaseDeAsalto(-1);
        } else {
            JOptionPane.showMessageDialog(this, "Aún hay personajes sin actuar");
        }
    }//GEN-LAST:event_jButton_avanzarFaseAsalto9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                CargaBase.iniciarTodo();
                new Principal().setVisible(true);

            }
        });

    }

    public void moverAccion(JPanelFormToken_Accion token, int destino) {
        token.getParent().remove(token);

        switch (destino) {
            case 0: {
                jPanel_sinAcciones_tokens.add(token);
                break;
            }
            case 1: {
                jPanel_campo_CargaSortilegios.add(token);
                break;
            }
            case 2: {
                jPanel_RealizaSortilegios_campo.add(token);
                break;
            }
            case 3: {
                jPanel_LanzaProyectiles_campo.add(token);
                break;
            }
            case 4: {
                jPanel_CargaProyectiles_campo.add(token);
                break;
            }
            case 5: {
                jPanel_PararProyectiles_campo.add(token);
                break;
            }
            case 6: {
                jPanel_movimientoYmaniobra_campo.add(token);
                break;
            }
            case 7: {
                jPanel_AtaqueCuerpoaCuerpo_campo.add(token);
                break;
            }
            case 8: {
                jPanel_Movimiento_campo.add(token);
                break;
            }
            case 9: {
                jPanel_MovimientoEstatic_campo.add(token);
                break;
            }
            default: {
                jPanel_campo_CargaSortilegios.add(token);
                break;
            }
        }

        this.repaint();

    }

    public void avanzarButtonFase(int fase) {
        fase = (fase == -1) ? butonFase +1 : fase;
        butonFase=fase;
        
                
                
        switch (fase) {
            case BUTTONFASE_DEFINICION: {               

                jButton_crear_pj.setEnabled(false);
                jButton_definir.setEnabled(false);
                jButton_comenzar.setEnabled(true);
                jButton_terminar.setEnabled(false);
                jButton_crear.setEnabled(false);
                jLabel_uso_ao.setVisible(false);

                //avanzarFaseDeAsalto(0);
                break;
            }
            case BUTTONFASE_DESARROLLO: {
               
                jLabel_uso_ao.setVisible(true);
                jButton_definir.setEnabled(false);
                jButton_comenzar.setEnabled(false);
                jButton_terminar.setEnabled(true);
                jButton_crear.setEnabled(false);

                avanzarFaseDeAsalto(ASALTOFASE_CARGA_SORTILEGIO);
                break;
            }
            case BUTTONFASE_RESULTADOS: {
               
                jLabel_uso_ao.setVisible(false);

                jButton_definir.setEnabled(true);
                jButton_comenzar.setEnabled(false);
                jButton_terminar.setEnabled(false);
                jButton_crear.setEnabled(false);
                jButton_crear_pj.setEnabled(true);

                break;
            }
            case BUTTONFASE_CREACION: {
               
                int nuevoAsalto = campo.resolverAsalto();
                jTextField_asalto.setText("" + nuevoAsalto);
                break;
            }

        }
        this.repaint();
    }

    public int faseActual() {
        return butonFase;
    }

    public int asaltoFaseActual() {
        return asaltoFase;
    }

    private void avanzarFaseDeAsalto(int pos) {
        pos = (pos == -1) ? asaltoFase + 1 : pos;
        if (pos > ASALTOFASE_MOVIMIENTO_ESTATICO) {
            int r = JOptionPane.showConfirmDialog(this, "Terminar el asalto?");
            if (JOptionPane.OK_OPTION == r) {
                avanzarButtonFase(BUTTONFASE_RESULTADOS);
            } else {
                asaltoFase = pos = ASALTOFASE_CARGA_SORTILEGIO;
            }

        }
        
        switch (pos) {
            case ASALTOFASE_CARGA_SORTILEGIO: {

                jButton_avanzarFaseAsalto9.setEnabled(false);
                jButton_avanzarFaseAsalto1.setEnabled(true);
                jPanel_Titulo_cargaSortilegios.setBackground(Color.red);
                jPanel_Titulo_SinAcciones.setBackground(new java.awt.Color(204, 204, 255));

                break;
            }
            case ASALTOFASE_REALIZA_SORTILEGIO: {

                jButton_avanzarFaseAsalto1.setEnabled(false);
                jButton_avanzarFaseAsalto2.setEnabled(true);
                jPanel_Titulo_RealizaSortilegios.setBackground(Color.red);
                jPanel_Titulo_cargaSortilegios.setBackground(new java.awt.Color(204, 204, 255));

                resolverTokens();

                break;
            }
            case ASALTOFASE_DISPARA_PROYECTIL: {

                jButton_avanzarFaseAsalto2.setEnabled(false);
                jButton_avanzarFaseAsalto3.setEnabled(true);
                jPanel_Titulo_DisparaProyectiles.setBackground(Color.red);
                jPanel_Titulo_RealizaSortilegios.setBackground(new java.awt.Color(204, 204, 255));

                resolverTokens();

                break;
            }
            case ASALTOFASE_CARGA_PROYECTIL: {

                jButton_avanzarFaseAsalto3.setEnabled(false);
                jButton_avanzarFaseAsalto4.setEnabled(true);
                jPanel_Titulo_cargaProyectiles.setBackground(Color.red);
                jPanel_Titulo_DisparaProyectiles.setBackground(new java.awt.Color(204, 204, 255));

                resolverTokens();

                break;
            }
            case ASALTOFASE_PARAR_PROYECTIL: {

                jButton_avanzarFaseAsalto4.setEnabled(false);
                jButton_avanzarFaseAsalto5.setEnabled(true);
                jPanel_Titulo_PararProyectiles.setBackground(Color.red);
                jPanel_Titulo_cargaProyectiles.setBackground(new java.awt.Color(204, 204, 255));

                resolverTokens();

                break;
            }
            case ASALTOFASE_MOVIMIENTO_Y_MANIOBRA: {

                jButton_avanzarFaseAsalto5.setEnabled(false);
                jButton_avanzarFaseAsalto6.setEnabled(true);
                jPanel_Titulo_movimientoYmaniobra.setBackground(Color.red);
                jPanel_Titulo_PararProyectiles.setBackground(new java.awt.Color(204, 204, 255));

                resolverTokens();

                break;
            }
            case ASALTOFASE_ATAQUE_CUERPO_A_CUERPO: {

                jButton_avanzarFaseAsalto6.setEnabled(false);
                jButton_avanzarFaseAsalto7.setEnabled(true);
                jPanel_Titulo_AtaqueCuerpoaCuerpo.setBackground(Color.red);
                jPanel_Titulo_movimientoYmaniobra.setBackground(new java.awt.Color(204, 204, 255));

                resolverTokens();

                break;
            }
            case ASALTOFASE_DESPLAZAMIENTO: {

                jButton_avanzarFaseAsalto7.setEnabled(false);
                jButton_avanzarFaseAsalto8.setEnabled(true);
                jPanel_Titulo_Movimiento.setBackground(Color.red);
                jPanel_Titulo_AtaqueCuerpoaCuerpo.setBackground(new java.awt.Color(204, 204, 255));

                resolverTokens();

                break;
            }
            case ASALTOFASE_MOVIMIENTO_ESTATICO: {

                jButton_avanzarFaseAsalto8.setEnabled(false);
                jButton_avanzarFaseAsalto9.setEnabled(true);
                jPanel_Titulo_MovimientoEstatico.setBackground(Color.red);
                jPanel_Titulo_Movimiento.setBackground(new java.awt.Color(204, 204, 255));

                resolverTokens();

                break;
            }
            case ASALTOFASE_SINACCION: {

                jButton_avanzarFaseAsalto9.setEnabled(false);
                jButton_avanzarFaseAsalto1.setEnabled(true);
                jPanel_Titulo_cargaSortilegios.setBackground(Color.red);
                jPanel_Titulo_MovimientoEstatico.setBackground(new java.awt.Color(204, 204, 255));

                resolverTokens();

                break;
            }
            default: {
                asaltoFase = ASALTOFASE_SINACCION;

                jButton_avanzarFaseAsalto1.setEnabled(false);

                jPanel_Titulo_cargaSortilegios.setBackground(Color.red);
                jPanel_Titulo_SinAcciones.setBackground(new java.awt.Color(204, 204, 255));

                resolverTokens();

                break;
            }
        }

        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_avanzarFaseAsalto1;
    private javax.swing.JButton jButton_avanzarFaseAsalto2;
    private javax.swing.JButton jButton_avanzarFaseAsalto3;
    private javax.swing.JButton jButton_avanzarFaseAsalto4;
    private javax.swing.JButton jButton_avanzarFaseAsalto5;
    private javax.swing.JButton jButton_avanzarFaseAsalto6;
    private javax.swing.JButton jButton_avanzarFaseAsalto7;
    private javax.swing.JButton jButton_avanzarFaseAsalto8;
    private javax.swing.JButton jButton_avanzarFaseAsalto9;
    private javax.swing.JButton jButton_comenzar;
    private javax.swing.JButton jButton_crear;
    private javax.swing.JButton jButton_crear_pj;
    private javax.swing.JButton jButton_definir;
    private javax.swing.JButton jButton_terminar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_uso_ao;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_Acciones;
    private javax.swing.JPanel jPanel_Asaltos_tab;
    private javax.swing.JPanel jPanel_Aslatos;
    private javax.swing.JPanel jPanel_AtaqueCuerpoaCuerpo;
    private javax.swing.JPanel jPanel_AtaqueCuerpoaCuerpo_campo;
    private javax.swing.JPanel jPanel_Campo_tab;
    private javax.swing.JPanel jPanel_CargaProyectiles;
    private javax.swing.JPanel jPanel_CargaProyectiles_campo;
    private javax.swing.JPanel jPanel_CargaSortilegios;
    private javax.swing.JPanel jPanel_General;
    private javax.swing.JPanel jPanel_LanzaProyectiles;
    private javax.swing.JPanel jPanel_LanzaProyectiles_campo;
    private javax.swing.JPanel jPanel_Movimiento;
    private javax.swing.JPanel jPanel_MovimientoEstatic_campo;
    private javax.swing.JPanel jPanel_MovimientoEstatico;
    private javax.swing.JPanel jPanel_Movimiento_campo;
    private javax.swing.JPanel jPanel_PararProyectiles;
    private javax.swing.JPanel jPanel_PararProyectiles_campo;
    private javax.swing.JPanel jPanel_Pjs;
    private javax.swing.JPanel jPanel_Pnj;
    private javax.swing.JPanel jPanel_RealizaSortilegios;
    private javax.swing.JPanel jPanel_RealizaSortilegios_campo;
    private javax.swing.JPanel jPanel_Resumen_tab;
    private javax.swing.JPanel jPanel_SinAcciones;
    private java.awt.ScrollPane jPanel_SinAcciones_panel;
    private javax.swing.JPanel jPanel_Titulo_AtaqueCuerpoaCuerpo;
    private javax.swing.JPanel jPanel_Titulo_DisparaProyectiles;
    private javax.swing.JPanel jPanel_Titulo_Movimiento;
    private javax.swing.JPanel jPanel_Titulo_MovimientoEstatico;
    private javax.swing.JPanel jPanel_Titulo_PararProyectiles;
    private javax.swing.JPanel jPanel_Titulo_RealizaSortilegios;
    private javax.swing.JPanel jPanel_Titulo_SinAcciones;
    private javax.swing.JPanel jPanel_Titulo_cargaProyectiles;
    private javax.swing.JPanel jPanel_Titulo_cargaSortilegios;
    private javax.swing.JPanel jPanel_Titulo_movimientoYmaniobra;
    private javax.swing.JPanel jPanel_campo_CargaSortilegios;
    private javax.swing.JPanel jPanel_movimientoYmaniobra;
    private javax.swing.JPanel jPanel_movimientoYmaniobra_campo;
    private javax.swing.JPanel jPanel_sinAcciones_tokens;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_asalto;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.ScrollPane scrollPane2;
    // End of variables declaration//GEN-END:variables

    static public boolean dosLados = false;
    static public javax.swing.JFrame ventana;
    public int butonFase = 0;
    public int asaltoFase = 0;
    private CampoDeBatalla campo;

    public static final int BUTTONFASE_CREACION = 0;
    public static final int BUTTONFASE_DEFINICION = 1;
    public static final int BUTTONFASE_DESARROLLO = 2;
    public static final int BUTTONFASE_RESULTADOS = 3;

    public static final int ASALTOFASE_SINACCION = 0;
    public static final int ASALTOFASE_CARGA_SORTILEGIO = 1;
    public static final int ASALTOFASE_REALIZA_SORTILEGIO = 2;
    public static final int ASALTOFASE_DISPARA_PROYECTIL = 3;
    public static final int ASALTOFASE_CARGA_PROYECTIL = 4;
    public static final int ASALTOFASE_PARAR_PROYECTIL = 5;
    public static final int ASALTOFASE_MOVIMIENTO_Y_MANIOBRA = 6;
    public static final int ASALTOFASE_ATAQUE_CUERPO_A_CUERPO = 7;
    public static final int ASALTOFASE_DESPLAZAMIENTO = 8;
    public static final int ASALTOFASE_MOVIMIENTO_ESTATICO = 9;

    private void resolverTokens() {
        System.out.println("aun no hace nada");
    }

    private boolean todosActuaron(JPanel jp) {
        for (int i = 0; i < jp.getComponentCount(); i++) {
            JPanelFormToken_Accion jpta = (JPanelFormToken_Accion) jp.getComponent(i);
            if (!jpta.isDone()) {
                if (!jpta.isAccionDeOportunidad()) {
                    return false;
                }
            }
        }
        return true;
    }

}
