/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superrolbattle;

import instancias.CampoDeBatalla;
import instancias.Token;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.awt.Point;
import java.util.Vector;
import java.util.concurrent.RecursiveAction;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import recursos.CargaBase;
import recursos.Recursos;
import static recursos.Recursos.verTabla;
import superrolbattle.ventanas.*;

/**
 *
 * @author Juan
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        
        setLocationRelativeTo(null);
        principal.ventana = this;
        JPanelFormToken jpft = new JPanelFormToken(Recursos.soldados.get(0));
        jPanel_Pnj.add(jpft);
        JPanelFormToken jpft2 = new JPanelFormToken(Recursos.soldados.get(1));
        jPanel_Pnj.add(jpft2);
        JPanelFormToken jpft3 = new JPanelFormToken(Recursos.soldados.get(2));
        jPanel_Pnj.add(jpft3);
        JPanelFormToken jpft4 = new JPanelFormToken(Recursos.soldados.get(2));
        jPanel_Pnj.add(jpft4);
        jPanel_Pnj.setLayout(new GridLayout(1, 4, 2, 2));
        this.pack();
        /* tablei = new MyTable(true);
        tabled = new MyTable(false);
        modeloTI = (MyTableModel) tablei.getModel();
        modeloTD = (MyTableModel) tabled.getModel();

        tablei.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Token tok = (Token) modeloTI.getValueAt(tablei.getSelectedRow(), 0);
                jTextField_NV.setText("" + tok.getNivel());
                jTextField_BO.setText("" + tok.getHabilidades().getBo());
                jTextField_BD.setText("" + tok.getHabilidades().getBd());
                jTextField_Arm.setText("" + tok.getHabilidades().getArmadura());
                jLabel_bi.setText(tok.getManoIZQ().getArmaEquipada().toString());
                jLabel_bd.setText(tok.getManoDER().getArmaEquipada().toString());
            }
        });
        tabled.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Token tok = (Token) modeloTD.getValueAt(tabled.getSelectedRow(), 0);
                jTextField_NV.setText("" + tok.getNivel());
                jTextField_BO.setText("" + tok.getHabilidades().getBo());
                jTextField_BD.setText("" + tok.getHabilidades().getBd());
                jTextField_Arm.setText("" + tok.getHabilidades().getArmadura());
                jLabel_bi.setText(tok.getManoIZQ().getArmaEquipada().toString());
                jLabel_bd.setText(tok.getManoDER().getArmaEquipada().toString());
            }
        });

        tablei.setAutoCreateRowSorter(true);
        tabled.setAutoCreateRowSorter(true);
        
        
        jScrollPane1.add(tablei);
        this.jScrollPane1.setViewportView(tablei);
        jPanel2.add(tabled);
        this.jScrollPane2.setViewportView(tabled);
         */
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel_General = new javax.swing.JPanel();
        jPanel_Acciones = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton_crear = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel_Campo = new javax.swing.JPanel();
        scrollPane1 = new java.awt.ScrollPane();
        jPanel_Pnj = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multiple Battle Simulator");
        setMinimumSize(new java.awt.Dimension(707, 349));
        setPreferredSize(null);

        jPanel_General.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_General.setAutoscrolls(true);
        jPanel_General.setMaximumSize(new java.awt.Dimension(720, 410));
        jPanel_General.setLayout(new java.awt.BorderLayout());

        jPanel_Acciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Acciones.setPreferredSize(new java.awt.Dimension(396, 54));
        jPanel_Acciones.setLayout(new javax.swing.BoxLayout(jPanel_Acciones, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setMaximumSize(new java.awt.Dimension(100007, 50));
        jPanel7.setMinimumSize(new java.awt.Dimension(300, 0));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jButton_crear.setText("Crear");
        jButton_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_crearActionPerformed(evt);
            }
        });
        jPanel7.add(jButton_crear);

        jButton2.setText("FIGHT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        jButton3.setText("Dañar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);

        jButton4.setText("Seleccionar/deseleccionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4);

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        jPanel_Acciones.add(jPanel7);

        jPanel_General.add(jPanel_Acciones, java.awt.BorderLayout.PAGE_START);

        jPanel_Campo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Campo.setAutoscrolls(true);
        jPanel_Campo.setLayout(new javax.swing.BoxLayout(jPanel_Campo, javax.swing.BoxLayout.LINE_AXIS));

        jPanel_Pnj.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel_PnjLayout = new javax.swing.GroupLayout(jPanel_Pnj);
        jPanel_Pnj.setLayout(jPanel_PnjLayout);
        jPanel_PnjLayout.setHorizontalGroup(
            jPanel_PnjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        jPanel_PnjLayout.setVerticalGroup(
            jPanel_PnjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        scrollPane1.add(jPanel_Pnj);

        jPanel_Campo.add(scrollPane1);

        jPanel_General.add(jPanel_Campo, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel_General, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("salir");
        jMenuItem3.setName("jMISalir"); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenuItem3.getAccessibleContext().setAccessibleDescription("");

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jCheckBoxMenuItem1.setText("Atacar al mismo Lado");
        jCheckBoxMenuItem1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxMenuItem1StateChanged(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Ayuda");

        jCheckBoxMenuItem2.setText("Imprimir por Consola");
        jCheckBoxMenuItem2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxMenuItem2ItemStateChanged(evt);
            }
        });
        jMenu5.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DañarToken dT = new DañarToken(this, true);
        dT.setVisible(true);
        dT.setLocationRelativeTo(this);
        dT.setLocation(new Point(this.getLocation()));
        this.pack();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_crearActionPerformed

        Object[] ObjTk = CrearToken.nuevoToken();
        boolean lado = (boolean) ObjTk[0];
        Token tk = (Token) ObjTk[1];
        Recursos.soldados.add(tk);
        if (tk != null) {
            Vector tok = Recursos.ObjSoldado(tk);
            if (lado) {
                modeloTI.addRow(tok);
            } else {
                modeloTD.addRow(tok);
            }
        }
    }//GEN-LAST:event_jButton_crearActionPerformed

    private void jCheckBoxMenuItem1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1StateChanged
        principal.dosLados = jCheckBoxMenuItem1.isSelected();
    }//GEN-LAST:event_jCheckBoxMenuItem1StateChanged

    private void jCheckBoxMenuItem2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ItemStateChanged
        Recursos.imprimirPorConsola = jCheckBoxMenuItem2.isSelected();
    }//GEN-LAST:event_jCheckBoxMenuItem2ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (CampoDeBatalla.puedenComenzarlosAtaques()) {
            CampoDeBatalla.resolverAsalto();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a =jPanel_Pnj.getComponentCount()/4+1;
        jPanel_Pnj.setLayout(new GridLayout(a, 4, 2, 2));
        
        JPanelFormToken jpft = new JPanelFormToken(Recursos.soldados.get(0));
        jPanel_Pnj.add(jpft);
        this.pack();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                CargaBase.iniciarTodo();
                new principal().setVisible(true);

            }
        });

    }

    private void adherirToken(Token unidad, JPanel lado) {

        JpToken jpT = new JpToken();
        this.setMinimumSize(this.getSize());
        this.setMaximumSize(this.getSize());
        this.setResizable(false);
        lado.add(jpT);
        jpT.setVisible(true);
        //lado.repaint();
        //jpT.repaint();

        this.pack();
        this.setMinimumSize(new Dimension(0, 0));
        this.setResizable(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_crear;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_Acciones;
    private javax.swing.JPanel jPanel_Campo;
    private javax.swing.JPanel jPanel_General;
    private javax.swing.JPanel jPanel_Pnj;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
    private MyTableModel modeloTI;
    private MyTableModel modeloTD;
    MyTable tablei;
    MyTable tabled;
    static public boolean dosLados = false;
    static public javax.swing.JFrame ventana;
}
