/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superrolbattle;

import instancias.CampoDeBatalla;
import instancias.Token;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.LayoutManager;
import java.awt.Point;
import java.util.Vector;
import java.util.concurrent.RecursiveAction;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import recursos.CargaBase;
import recursos.Recursos;
import static recursos.Recursos.verTabla;
import superrolbattle.ventanas.*;

/**
 *
 * @author Juan
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        setLocationRelativeTo(null);
        principal.ventana = this;
        tablei = new MyTable(true);
        tabled = new MyTable(false);
        modeloTI = (MyTableModel) tablei.getModel();
        modeloTD = (MyTableModel) tabled.getModel();

        tablei.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Token tok = (Token) modeloTI.getValueAt(tablei.getSelectedRow(), 0);
                jTextField_NV.setText("" + tok.getNivel());
                jTextField_BO.setText("" + tok.getHabilidades().getBo());
                jTextField_BD.setText("" + tok.getHabilidades().getBd());
                jTextField_Arm.setText("" + tok.getHabilidades().getArmadura());
                jLabel_bi.setText(tok.getManoIZQ().getArmaEquipada().toString());
                jLabel_bd.setText(tok.getManoDER().getArmaEquipada().toString());
            }
        });
        tabled.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Token tok = (Token) modeloTD.getValueAt(tabled.getSelectedRow(), 0);
                jTextField_NV.setText("" + tok.getNivel());
                jTextField_BO.setText("" + tok.getHabilidades().getBo());
                jTextField_BD.setText("" + tok.getHabilidades().getBd());
                jTextField_Arm.setText("" + tok.getHabilidades().getArmadura());
                jLabel_bi.setText(tok.getManoIZQ().getArmaEquipada().toString());
                jLabel_bd.setText(tok.getManoDER().getArmaEquipada().toString());
            }
        });

        tablei.setAutoCreateRowSorter(true);
        tabled.setAutoCreateRowSorter(true);
        
        
        jScrollPane1.add(tablei);
        this.jScrollPane1.setViewportView(tablei);
        jPanel2.add(tabled);
        this.jScrollPane2.setViewportView(tabled);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel_General = new javax.swing.JPanel();
        jPanel_Acciones = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton_crear = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel_NV = new javax.swing.JLabel();
        jTextField_NV = new javax.swing.JTextField();
        jLabel_BO = new javax.swing.JLabel();
        jTextField_BO = new javax.swing.JTextField();
        jLabel_BD = new javax.swing.JLabel();
        jTextField_BD = new javax.swing.JTextField();
        jLabel_Arm = new javax.swing.JLabel();
        jTextField_Arm = new javax.swing.JTextField();
        jPanel_Brazos = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel_bd = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_bi = new javax.swing.JLabel();
        jPanel_Campo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(707, 349));

        jPanel_General.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_General.setAutoscrolls(true);
        jPanel_General.setMaximumSize(new java.awt.Dimension(720, 410));
        jPanel_General.setLayout(new java.awt.BorderLayout());

        jPanel_Acciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Acciones.setPreferredSize(new java.awt.Dimension(396, 54));
        jPanel_Acciones.setLayout(new javax.swing.BoxLayout(jPanel_Acciones, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setMaximumSize(new java.awt.Dimension(100007, 50));
        jPanel7.setMinimumSize(new java.awt.Dimension(300, 0));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jButton_crear.setText("Crear");
        jButton_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_crearActionPerformed(evt);
            }
        });
        jPanel7.add(jButton_crear);

        jButton2.setText("FIGHT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        jButton3.setText("Dañar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);

        jButton4.setText("Seleccionar/deseleccionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        jPanel_Acciones.add(jPanel7);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setMaximumSize(new java.awt.Dimension(1331, 47));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel_NV.setText("NV");
        jPanel3.add(jLabel_NV);

        jTextField_NV.setEditable(false);
        jTextField_NV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_NV.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_NV.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField_NV.setMaximumSize(new java.awt.Dimension(35, 26));
        jTextField_NV.setMinimumSize(new java.awt.Dimension(35, 26));
        jTextField_NV.setPreferredSize(new java.awt.Dimension(35, 26));
        jPanel3.add(jTextField_NV);

        jLabel_BO.setText("BO");
        jPanel3.add(jLabel_BO);

        jTextField_BO.setEditable(false);
        jTextField_BO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_BO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_BO.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField_BO.setMaximumSize(new java.awt.Dimension(35, 26));
        jTextField_BO.setMinimumSize(new java.awt.Dimension(35, 26));
        jTextField_BO.setPreferredSize(new java.awt.Dimension(35, 26));
        jPanel3.add(jTextField_BO);

        jLabel_BD.setText("BD");
        jPanel3.add(jLabel_BD);

        jTextField_BD.setEditable(false);
        jTextField_BD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_BD.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_BD.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField_BD.setMaximumSize(new java.awt.Dimension(35, 26));
        jTextField_BD.setMinimumSize(new java.awt.Dimension(35, 26));
        jTextField_BD.setPreferredSize(new java.awt.Dimension(35, 26));
        jPanel3.add(jTextField_BD);

        jLabel_Arm.setText("Arm");
        jPanel3.add(jLabel_Arm);

        jTextField_Arm.setEditable(false);
        jTextField_Arm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Arm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_Arm.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField_Arm.setMaximumSize(new java.awt.Dimension(35, 26));
        jTextField_Arm.setMinimumSize(new java.awt.Dimension(35, 26));
        jTextField_Arm.setPreferredSize(new java.awt.Dimension(35, 26));
        jPanel3.add(jTextField_Arm);

        jPanel_Brazos.setMaximumSize(new java.awt.Dimension(1126, 41));
        jPanel_Brazos.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel_Brazos.setLayout(new javax.swing.BoxLayout(jPanel_Brazos, javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Brazo D."));
        jPanel6.setMaximumSize(new java.awt.Dimension(222, 35));
        jPanel6.setMinimumSize(new java.awt.Dimension(60, 35));
        jPanel6.setPreferredSize(new java.awt.Dimension(60, 35));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel_bd.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel_bd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel_bd, java.awt.BorderLayout.CENTER);

        jPanel_Brazos.add(jPanel6);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Brazo I."));
        jPanel5.setMaximumSize(new java.awt.Dimension(222, 35));
        jPanel5.setMinimumSize(new java.awt.Dimension(60, 35));
        jPanel5.setPreferredSize(new java.awt.Dimension(60, 35));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel_bi.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel_bi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_bi.setText("          ");
        jPanel5.add(jLabel_bi, java.awt.BorderLayout.CENTER);

        jPanel_Brazos.add(jPanel5);

        jPanel3.add(jPanel_Brazos);

        jPanel_Acciones.add(jPanel3);

        jPanel_General.add(jPanel_Acciones, java.awt.BorderLayout.PAGE_START);

        jPanel_Campo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Campo.setAutoscrolls(true);
        jPanel_Campo.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel2);

        jPanel_Campo.add(jScrollPane1);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(jPanel1);

        jPanel_Campo.add(jScrollPane2);

        jPanel_General.add(jPanel_Campo, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("salir");
        jMenuItem3.setName("jMISalir"); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenuItem3.getAccessibleContext().setAccessibleDescription("");

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jCheckBoxMenuItem1.setText("Atacar al mismo Lado");
        jCheckBoxMenuItem1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxMenuItem1StateChanged(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Ayuda");

        jCheckBoxMenuItem2.setText("Imprimir por Consola");
        jCheckBoxMenuItem2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxMenuItem2ItemStateChanged(evt);
            }
        });
        jMenu5.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_General, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_General, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DañarToken dT = new DañarToken(this, true);
        dT.setVisible(true);
        dT.setLocationRelativeTo(this);
        dT.setLocation(new Point(this.getLocation()));
        this.pack();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_crearActionPerformed

        Object[] ObjTk = CrearToken.nuevoToken();
        boolean lado = (boolean) ObjTk[0];
        Token tk = (Token) ObjTk[1];
        Recursos.soldados.add(tk);
        if (tk != null) {
            Vector tok = Recursos.ObjSoldado(tk);
            if (lado) {
                modeloTI.addRow(tok);
            } else {
                modeloTD.addRow(tok);
            }
        }
    }//GEN-LAST:event_jButton_crearActionPerformed

    private void jCheckBoxMenuItem1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1StateChanged
        principal.dosLados = jCheckBoxMenuItem1.isSelected();
    }//GEN-LAST:event_jCheckBoxMenuItem1StateChanged

    private void jCheckBoxMenuItem2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ItemStateChanged
       Recursos.imprimirPorConsola = jCheckBoxMenuItem2.isSelected();
    }//GEN-LAST:event_jCheckBoxMenuItem2ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       CampoDeBatalla.resolverAsalto();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Recursos.informar("HOla Kyoros");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                CargaBase.iniciarTodo();
                new principal().setVisible(true);

            }
        });

    }

    private void adherirToken(Token unidad, JPanel lado) {

        JpToken jpT = new JpToken();
        this.setMinimumSize(this.getSize());
        this.setMaximumSize(this.getSize());
        this.setResizable(false);
        lado.add(jpT);
        jpT.setVisible(true);
        //lado.repaint();
        //jpT.repaint();

        this.pack();
        this.setMinimumSize(new Dimension(0, 0));
        this.setResizable(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_crear;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Arm;
    private javax.swing.JLabel jLabel_BD;
    private javax.swing.JLabel jLabel_BO;
    private javax.swing.JLabel jLabel_NV;
    private javax.swing.JLabel jLabel_bd;
    private javax.swing.JLabel jLabel_bi;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_Acciones;
    private javax.swing.JPanel jPanel_Brazos;
    private javax.swing.JPanel jPanel_Campo;
    private javax.swing.JPanel jPanel_General;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_Arm;
    private javax.swing.JTextField jTextField_BD;
    private javax.swing.JTextField jTextField_BO;
    private javax.swing.JTextField jTextField_NV;
    // End of variables declaration//GEN-END:variables
    private MyTableModel modeloTI;
    private MyTableModel modeloTD;
    MyTable tablei;
    MyTable tabled;
    static public boolean dosLados = false;
    static public javax.swing.JFrame ventana;
}
