/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superrolbattle.ventanas;

import instancias.ListaDeSortilegios;
import instancias.Sortilegio;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import recursos.DataRecursos;
import superrolbattle.Principal;

/**
 *
 * @author TiranoJuan
 */
public class AdministrarListasSortilegios extends javax.swing.JDialog {

    /**
     * Creates new form AdministrarListasSortilegios
     */
    public AdministrarListasSortilegios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelo = (DefaultTableModel) jTable1.getModel();
        
        for (Map.Entry<Integer, ListaDeSortilegios> entry : hmlds.entrySet()) {            
            ListaDeSortilegios value = entry.getValue();
            jComboBox_Listas.addItem(value.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox_Listas = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Dominio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Tipo_lista = new javax.swing.JTextField();
        jButton_ns = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrar Listas de Sortilegio");

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jComboBox_Listas.setPreferredSize(new java.awt.Dimension(256, 20));
        jComboBox_Listas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ListasItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox_Listas);

        jButton2.setText("Nueva Lista");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lv", "Nombre", "AreaEfecto", "Duracion", "Alcance", "Descripcion", "Clase"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Dominio");
        jPanel4.add(jLabel1);

        jTextField_Dominio.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jTextField_Dominio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Dominio.setMinimumSize(new java.awt.Dimension(156, 20));
        jTextField_Dominio.setPreferredSize(new java.awt.Dimension(156, 20));
        jPanel4.add(jTextField_Dominio);

        jLabel2.setText("Tipo de Lista");
        jPanel4.add(jLabel2);

        jTextField_Tipo_lista.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jTextField_Tipo_lista.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Tipo_lista.setMinimumSize(new java.awt.Dimension(156, 20));
        jTextField_Tipo_lista.setPreferredSize(new java.awt.Dimension(156, 20));
        jPanel4.add(jTextField_Tipo_lista);

        jButton_ns.setText("Nuevo Sortilegio");
        jButton_ns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nsActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_ns);

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("Cerrar");
        jPanel3.add(jButton1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ListaDeSortilegios lds = CrearListaSortilegio.NuevaListaDeSortilegios(null, true);
        if (lds != null){
            Principal.crearListaDeSortilegiosNueva(lds);
            jComboBox_Listas.addItem(lds.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox_ListasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ListasItemStateChanged
        if (hmlds.containsKey(jComboBox_Listas.getSelectedIndex())){
            jTextField_Dominio.setText(ListaDeSortilegios.getDominioStr(hmlds.get(jComboBox_Listas.getSelectedIndex()).getDominio()));
            jTextField_Tipo_lista.setText(ListaDeSortilegios.txtTipoLista(hmlds.get(jComboBox_Listas.getSelectedIndex()).getTipo_lista()));
        }
    }//GEN-LAST:event_jComboBox_ListasItemStateChanged

    private void jButton_nsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nsActionPerformed
       int s = jComboBox_Listas.getSelectedIndex();
       int lv = NuevoSortilegio.Crear(null, rootPaneCheckingEnabled, hmlds.get(s));
       agregarSortilegioaLatabla(hmlds.get(s).getSortilegio(lv));
    }//GEN-LAST:event_jButton_nsActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_ns;
    private javax.swing.JComboBox<String> jComboBox_Listas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Dominio;
    private javax.swing.JTextField jTextField_Tipo_lista;
    // End of variables declaration//GEN-END:variables

    HashMap<Integer,ListaDeSortilegios> hmlds = Principal.dataRecursos.getListasDeSortilegios();
    DefaultTableModel modelo;

    private void agregarSortilegioaLatabla(Sortilegio s) {
        Object[] sort = {s.getNombre(),s.getLv(),s.getAreaDeEfecto(),s.getDuracion(),s.getAlcance(),s.getDescp(),s.getClase()};
        modelo.addRow(sort);
    }
}
