/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superrolbattle.ventanas;

/**
 *
 * @author Juan
 */
public class AlterararToken extends javax.swing.JDialog {

    /**
     * Creates new form DañarToken
     */
    public AlterararToken(java.awt.Frame parent, boolean modal, JPanelFormToken_Accion token) {
        super(parent, modal);
        initComponents();
        
       this.token = token;
       
       
       
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_pv = new javax.swing.JComboBox();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSpinner_sangrado = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner_obligado_a_parar = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner_Aturdido = new javax.swing.JSpinner();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner_AturdidoSinParar = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner_asParamoriri = new javax.swing.JSpinner();
        jPanel25 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSpinner_penalizacion_Actividad = new javax.swing.JSpinner();
        jPanel18 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        jPanel21 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSpinner_Aturdido2 = new javax.swing.JSpinner();
        jPanel20 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSpinner_Aturdido1 = new javax.swing.JSpinner();
        jPanel22 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSpinner8 = new javax.swing.JSpinner();
        jPanel23 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        jPanel24 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSpinner6 = new javax.swing.JSpinner();
        jPanel26 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jPanel3_Status = new javax.swing.JPanel();
        jPanel_Miembros = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jPanel16 = new javax.swing.JPanel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jPanel29 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel31 = new javax.swing.JPanel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jPanel30 = new javax.swing.JPanel();
        jPanel_descripcion = new javax.swing.JPanel();
        jScrollPane_Resumen = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel_Aceptar_cancelar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("P. V:");
        jPanel4.add(jLabel1, java.awt.BorderLayout.WEST);

        jComboBox_pv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75" }));
        jComboBox_pv.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox_pv.setMaximumSize(new java.awt.Dimension(50, 20));
        jComboBox_pv.setMinimumSize(new java.awt.Dimension(50, 20));
        jComboBox_pv.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel4.add(jComboBox_pv, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel4);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Pv Sangrado");
        jPanel11.add(jLabel7, java.awt.BorderLayout.WEST);

        jSpinner_sangrado.setModel(new javax.swing.SpinnerNumberModel(0, 0, 25, 1));
        jSpinner_sangrado.setMinimumSize(new java.awt.Dimension(50, 20));
        jSpinner_sangrado.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel11.add(jSpinner_sangrado, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel11);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Asaltos Obligado a Parar");
        jPanel7.add(jLabel4, java.awt.BorderLayout.WEST);

        jSpinner_obligado_a_parar.setModel(new javax.swing.SpinnerNumberModel(0, 0, 25, 1));
        jSpinner_obligado_a_parar.setMinimumSize(new java.awt.Dimension(50, 20));
        jSpinner_obligado_a_parar.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel7.add(jSpinner_obligado_a_parar, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel7);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Asaltos Aturdido");
        jPanel6.add(jLabel3, java.awt.BorderLayout.WEST);

        jSpinner_Aturdido.setModel(new javax.swing.SpinnerNumberModel(0, 0, 25, 1));
        jSpinner_Aturdido.setMinimumSize(new java.awt.Dimension(50, 20));
        jSpinner_Aturdido.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel6.add(jSpinner_Aturdido, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel6);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("As. Aturdido y sin parar");
        jPanel8.add(jLabel5, java.awt.BorderLayout.WEST);

        jSpinner_AturdidoSinParar.setModel(new javax.swing.SpinnerNumberModel(0, 0, 25, 1));
        jSpinner_AturdidoSinParar.setMinimumSize(new java.awt.Dimension(50, 20));
        jSpinner_AturdidoSinParar.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel8.add(jSpinner_AturdidoSinParar, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Asaltos para Morir");
        jPanel9.add(jLabel6, java.awt.BorderLayout.WEST);

        jSpinner_asParamoriri.setModel(new javax.swing.SpinnerNumberModel(0, 0, 25, 1));
        jSpinner_asParamoriri.setMinimumSize(new java.awt.Dimension(50, 20));
        jSpinner_asParamoriri.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel9.add(jSpinner_asParamoriri, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel9);

        jPanel25.setLayout(new java.awt.BorderLayout());

        jLabel13.setText("Penalizacion Actividad");
        jPanel25.add(jLabel13, java.awt.BorderLayout.WEST);

        jSpinner_penalizacion_Actividad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 250, 5));
        jSpinner_penalizacion_Actividad.setMinimumSize(new java.awt.Dimension(50, 20));
        jSpinner_penalizacion_Actividad.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel25.add(jSpinner_penalizacion_Actividad, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel25);

        jPanel1.add(jPanel2);

        jTabbedPane1.addTab("Daños", jPanel1);

        jPanel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Recupera P. V:");
        jPanel19.add(jLabel2, java.awt.BorderLayout.WEST);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75" }));
        jComboBox8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox8.setMaximumSize(new java.awt.Dimension(50, 20));
        jComboBox8.setMinimumSize(new java.awt.Dimension(50, 20));
        jComboBox8.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel19.add(jComboBox8, java.awt.BorderLayout.EAST);

        jPanel17.add(jPanel19);

        jPanel21.setLayout(new java.awt.BorderLayout());

        jLabel9.setText("Sana Pv Sangrado");
        jPanel21.add(jLabel9, java.awt.BorderLayout.WEST);

        jSpinner_Aturdido2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 25, 1));
        jSpinner_Aturdido2.setMinimumSize(new java.awt.Dimension(50, 20));
        jSpinner_Aturdido2.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel21.add(jSpinner_Aturdido2, java.awt.BorderLayout.EAST);

        jPanel17.add(jPanel21);

        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel8.setText("Recupera Asaltos Aturdido");
        jPanel20.add(jLabel8, java.awt.BorderLayout.WEST);

        jSpinner_Aturdido1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 25, 1));
        jSpinner_Aturdido1.setMinimumSize(new java.awt.Dimension(50, 20));
        jSpinner_Aturdido1.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel20.add(jSpinner_Aturdido1, java.awt.BorderLayout.EAST);

        jPanel17.add(jPanel20);

        jPanel22.setLayout(new java.awt.BorderLayout());

        jLabel10.setText("Recupera o Bon. Actividad");
        jPanel22.add(jLabel10, java.awt.BorderLayout.WEST);

        jSpinner8.setModel(new javax.swing.SpinnerNumberModel(0, 0, 250, 5));
        jSpinner8.setMinimumSize(new java.awt.Dimension(50, 20));
        jSpinner8.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel22.add(jSpinner8, java.awt.BorderLayout.EAST);

        jPanel17.add(jPanel22);

        jPanel23.setLayout(new java.awt.BorderLayout());

        jLabel11.setText("Bono BD");
        jPanel23.add(jLabel11, java.awt.BorderLayout.WEST);

        jSpinner7.setModel(new javax.swing.SpinnerNumberModel(0, 0, 250, 5));
        jSpinner7.setMinimumSize(new java.awt.Dimension(50, 20));
        jSpinner7.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel23.add(jSpinner7, java.awt.BorderLayout.EAST);

        jPanel17.add(jPanel23);

        jPanel24.setLayout(new java.awt.BorderLayout());

        jLabel12.setText("Bono BD");
        jPanel24.add(jLabel12, java.awt.BorderLayout.WEST);

        jSpinner6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 250, 5));
        jSpinner6.setMinimumSize(new java.awt.Dimension(50, 20));
        jSpinner6.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel24.add(jSpinner6, java.awt.BorderLayout.EAST);

        jPanel17.add(jPanel24);

        jPanel26.setLayout(new java.awt.BorderLayout());

        jLabel14.setText("Bono RT");
        jPanel26.add(jLabel14, java.awt.BorderLayout.WEST);

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 250, 5));
        jSpinner3.setMinimumSize(new java.awt.Dimension(50, 20));
        jSpinner3.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel26.add(jSpinner3, java.awt.BorderLayout.EAST);

        jPanel17.add(jPanel26);

        jPanel18.add(jPanel17, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Recuperacion/buff", jPanel18);

        jPanel10.add(jTabbedPane1);

        jPanel3_Status.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3_Status.setLayout(new javax.swing.BoxLayout(jPanel3_Status, javax.swing.BoxLayout.LINE_AXIS));

        jPanel_Miembros.setBorder(javax.swing.BorderFactory.createTitledBorder("Miembros Inutilizados"));
        jPanel_Miembros.setLayout(new javax.swing.BoxLayout(jPanel_Miembros, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.PAGE_AXIS));

        jCheckBox4.setText("Brazo Izquierdo");
        jPanel15.add(jCheckBox4);

        jCheckBox5.setText("Brazo Derecho");
        jPanel15.add(jCheckBox5);

        jPanel_Miembros.add(jPanel15);

        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.PAGE_AXIS));

        jCheckBox6.setText("Pierna Izquierda");
        jPanel16.add(jCheckBox6);

        jCheckBox7.setText("Pierna Derecha");
        jPanel16.add(jCheckBox7);

        jPanel_Miembros.add(jPanel16);

        jPanel3_Status.add(jPanel_Miembros);

        jPanel29.setLayout(new javax.swing.BoxLayout(jPanel29, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel12.setLayout(new java.awt.GridLayout(1, 2));

        jCheckBox1.setText("Muerto");
        jPanel12.add(jCheckBox1);

        jPanel29.add(jPanel12);

        jPanel13.setLayout(new java.awt.GridLayout(1, 2));

        jCheckBox2.setText("Inconsciente");
        jPanel13.add(jCheckBox2);

        jPanel29.add(jPanel13);

        jPanel14.setLayout(new java.awt.GridLayout(1, 2));

        jCheckBox3.setText("Coma");
        jPanel14.add(jCheckBox3);

        jPanel29.add(jPanel14);

        jPanel31.setLayout(new java.awt.GridLayout(1, 2));

        jCheckBox11.setText("Postrado");
        jPanel31.add(jCheckBox11);

        jPanel29.add(jPanel31);

        jPanel3_Status.add(jPanel29);

        jPanel10.add(jPanel3_Status);

        getContentPane().add(jPanel10);

        jPanel30.setLayout(new javax.swing.BoxLayout(jPanel30, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_descripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion"));
        jPanel_descripcion.setLayout(new javax.swing.BoxLayout(jPanel_descripcion, javax.swing.BoxLayout.LINE_AXIS));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane_Resumen.setViewportView(jTextArea1);

        jPanel_descripcion.add(jScrollPane_Resumen);

        jPanel30.add(jPanel_descripcion);

        jPanel_Aceptar_cancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Aceptar_cancelar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("Acptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel_Aceptar_cancelar.add(jButton1);

        jButton2.setText("cancelar");
        jPanel_Aceptar_cancelar.add(jButton2);

        jPanel30.add(jPanel_Aceptar_cancelar);

        getContentPane().add(jPanel30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox_pv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel3_Status;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_Aceptar_cancelar;
    private javax.swing.JPanel jPanel_Miembros;
    private javax.swing.JPanel jPanel_descripcion;
    private javax.swing.JScrollPane jScrollPane_Resumen;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner_Aturdido;
    private javax.swing.JSpinner jSpinner_Aturdido1;
    private javax.swing.JSpinner jSpinner_Aturdido2;
    private javax.swing.JSpinner jSpinner_AturdidoSinParar;
    private javax.swing.JSpinner jSpinner_asParamoriri;
    private javax.swing.JSpinner jSpinner_obligado_a_parar;
    private javax.swing.JSpinner jSpinner_penalizacion_Actividad;
    private javax.swing.JSpinner jSpinner_sangrado;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    private JPanelFormToken_Accion token;
}
