/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superrolbattle.ventanas;

import instancias.Accion;
import instancias.Token;
import instancias.properties.Arma;
import instancias.properties.Bo;
import instancias.properties.Extremidad;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import static recursos.Constantes.CLASE_ESCUDO;
import superrolbattle.Principal;
import instancias.properties.DatosCombate;
import javax.swing.JSlider;

/**
 *
 * @author TiranoJuan
 */
public class CombatesCuerpoACuerpo extends javax.swing.JDialog {

    /**
     * Creates new form CombatesCuerpoACuerpo
     */
    public CombatesCuerpoACuerpo(java.awt.Frame parent, boolean modal, Principal principal) {
        super(parent, modal);
        initComponents();
        this.principal = principal;

        ArrayList<JPanelFormToken_Accion> combs = principal.getCombatesCaC();
        DefaultListModel jdlm = (DefaultListModel) jList_combatientes.getModel();
        for (JPanelFormToken_Accion jpta : combs) {
            jdlm.addElement(jpta);
        }
        jList_combatientes.setModel(jdlm);
        //jComboBox_enemigos.setModel(new DefaultComboBoxModel(principal.getTodosLosJPanelEnemigos(jpta.getToken()).toArray()));

    }

    private void agregarArmasALalista(Arma a) {

        if (a != null) {
            

        }
    }

    private void agregarBlanco(Token t) {
        if (t != null) {
            DefaultListModel jdlm = (DefaultListModel) jList_blancos.getModel();
            jdlm.addElement(t);
            jList_blancos.setModel(jdlm);

        }
    }

    private void seleccionarPersonaje() {

        jSpinner_cant_cambios.setValue(0);
        DefaultListModel jdlm = (DefaultListModel) jList_combatientes.getModel();
        JPanelFormToken_Accion jpta = (JPanelFormToken_Accion) jdlm.getElementAt(jList_combatientes.getSelectedIndex());
        
        //jComboBox_enemigos.setModel(new DefaultComboBoxModel());
        jdlm = (DefaultListModel) jList_blancos.getModel();
        jdlm.removeAllElements();
        for (Object enemigo : principal.getTodosLosJPanelEnemigos(jpta.getToken()).toArray()) {
            enemigo = (JPanelFormToken_Accion) enemigo;
            jdlm.addElement(enemigo);
        }
        jList_blancos.setModel(jdlm);

        Accion a = jpta.getAccion();
        DatosCombate dc = a.getCombate();
        jTextField_boDisponible.setText(dc.getBo_Disponible() + "");
        jSpinner_cant_cambios.setValue(dc.getCantidadCambios());

        jdlm = (DefaultListModel) jList_armas.getModel();
        jdlm.removeAllElements();
        for (Extremidad ext : jpta.getToken().getExtremidades()) {
            Arma arma = ext.getArmaEquipada();
            if (arma != null) {                
                jdlm.addElement(arma);               
            }
        }
        jList_armas.setModel(jdlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_north = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_center_left = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_combatientes = new javax.swing.JList<>();
        jPanel_center = new javax.swing.JPanel();
        jPanel_BO = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_boDisponible = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel_armas = new javax.swing.JPanel();
        jScrollPane_armasPuestas = new javax.swing.JScrollPane();
        jList_armas = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner_cant_cambios = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jButton_atacar = new javax.swing.JButton();
        jPanel_center_right = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_blancos = new javax.swing.JList<>();
        jPanel_souyh = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton_cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Combates Cuerpo a Cuerpo");

        jLabel1.setText("Combates Cuerpo a Cuerpo");

        javax.swing.GroupLayout jPanel_northLayout = new javax.swing.GroupLayout(jPanel_north);
        jPanel_north.setLayout(jPanel_northLayout);
        jPanel_northLayout.setHorizontalGroup(
            jPanel_northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
            .addGroup(jPanel_northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_northLayout.createSequentialGroup()
                    .addGap(0, 170, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 171, Short.MAX_VALUE)))
        );
        jPanel_northLayout.setVerticalGroup(
            jPanel_northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
            .addGroup(jPanel_northLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_northLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel_north, java.awt.BorderLayout.NORTH);

        jPanel_center_left.setMaximumSize(null);
        jPanel_center_left.setMinimumSize(new java.awt.Dimension(120, 330));
        jPanel_center_left.setPreferredSize(new java.awt.Dimension(120, 297));
        jPanel_center_left.setLayout(new javax.swing.BoxLayout(jPanel_center_left, javax.swing.BoxLayout.LINE_AXIS));

        jList_combatientes.setModel(new DefaultListModel());
        jList_combatientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_combatientesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList_combatientes);

        jPanel_center_left.add(jScrollPane2);

        getContentPane().add(jPanel_center_left, java.awt.BorderLayout.WEST);

        jPanel_center.setLayout(new javax.swing.BoxLayout(jPanel_center, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_BO.setMaximumSize(new java.awt.Dimension(10000010, 50));
        jPanel_BO.setMinimumSize(new java.awt.Dimension(110, 50));
        jPanel_BO.setPreferredSize(new java.awt.Dimension(110, 50));

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        jLabel2.setText("BO");
        jPanel_BO.add(jLabel2);

        jTextField_boDisponible.setEditable(false);
        jTextField_boDisponible.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        jTextField_boDisponible.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_boDisponible.setText("100");
        jTextField_boDisponible.setMinimumSize(new java.awt.Dimension(100, 40));
        jTextField_boDisponible.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel_BO.add(jTextField_boDisponible);

        jPanel_center.add(jPanel_BO);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel_armas.setMinimumSize(new java.awt.Dimension(23, 123));
        jPanel_armas.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel_armas.setLayout(new javax.swing.BoxLayout(jPanel_armas, javax.swing.BoxLayout.PAGE_AXIS));

        jList_armas.setModel(new DefaultListModel());
        jList_armas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_armasValueChanged(evt);
            }
        });
        jScrollPane_armasPuestas.setViewportView(jList_armas);

        jPanel_armas.add(jScrollPane_armasPuestas);

        jButton5.setText("Quitar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5);

        jButton6.setText("Agregar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6);

        jPanel_armas.add(jPanel7);

        jPanel2.add(jPanel_armas);

        jLabel3.setText("Cambios de Equipo");
        jPanel1.add(jLabel3);

        jSpinner_cant_cambios.setMinimumSize(new java.awt.Dimension(129, 20));
        jSpinner_cant_cambios.setPreferredSize(new java.awt.Dimension(39, 20));
        jSpinner_cant_cambios.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_cant_cambiosStateChanged(evt);
            }
        });
        jPanel1.add(jSpinner_cant_cambios);

        jPanel2.add(jPanel1);

        jButton_atacar.setText("ATACAR");
        jButton_atacar.setEnabled(false);
        jButton_atacar.setMinimumSize(new java.awt.Dimension(123, 33));
        jButton_atacar.setPreferredSize(new java.awt.Dimension(123, 33));
        jButton_atacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atacarActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_atacar);

        jPanel2.add(jPanel3);

        jPanel_center.add(jPanel2);

        getContentPane().add(jPanel_center, java.awt.BorderLayout.CENTER);

        jPanel_center_right.setMinimumSize(new java.awt.Dimension(120, 330));
        jPanel_center_right.setPreferredSize(new java.awt.Dimension(120, 297));
        jPanel_center_right.setLayout(new javax.swing.BoxLayout(jPanel_center_right, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel4.setText("Enemigos");
        jPanel_center_right.add(jLabel4);

        jList_blancos.setModel(new DefaultListModel());
        jList_blancos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_blancosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList_blancos);

        jPanel_center_right.add(jScrollPane1);

        getContentPane().add(jPanel_center_right, java.awt.BorderLayout.EAST);

        jPanel_souyh.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("Siguiente PJ");
        jPanel_souyh.add(jButton1);

        jButton_cerrar.setText("Cerrar");
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });
        jPanel_souyh.add(jButton_cerrar);

        getContentPane().add(jPanel_souyh, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList_combatientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_combatientesValueChanged
        seleccionarPersonaje();
    }//GEN-LAST:event_jList_combatientesValueChanged

    private void jSpinner_cant_cambiosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_cant_cambiosStateChanged
        modificarBO();
    }//GEN-LAST:event_jSpinner_cant_cambiosStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        guardarArma();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        equiparArma();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jList_blancosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_blancosValueChanged
        modificarBO();
        activarAtaqueButton();
    }//GEN-LAST:event_jList_blancosValueChanged

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void jButton_atacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atacarActionPerformed
       iniciarAtaques();
    }//GEN-LAST:event_jButton_atacarActionPerformed

    private void jList_armasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_armasValueChanged
        activarAtaqueButton();
    }//GEN-LAST:event_jList_armasValueChanged

    private void modificarBO() {
        DefaultListModel jdlm = (DefaultListModel) jList_combatientes.getModel();
        JPanelFormToken_Accion jpta = (JPanelFormToken_Accion) jdlm.getElementAt(jList_combatientes.getSelectedIndex());
        
        int cant = (Integer) jSpinner_cant_cambios.getValue();
        int bon = jpta.getAccion().getCombate().getBo_Disponible();        
        int bono_ene = (jList_blancos.getSelectedIndices().length >1)? (jList_blancos.getSelectedIndices().length-1)*-50 :0;
        bon = (cant * -30) + bon +  bono_ene;
        jTextField_boDisponible.setText("" + bon);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton_atacar;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList_armas;
    private javax.swing.JList<String> jList_blancos;
    private javax.swing.JList<String> jList_combatientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_BO;
    private javax.swing.JPanel jPanel_armas;
    private javax.swing.JPanel jPanel_center;
    private javax.swing.JPanel jPanel_center_left;
    private javax.swing.JPanel jPanel_center_right;
    private javax.swing.JPanel jPanel_north;
    private javax.swing.JPanel jPanel_souyh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane_armasPuestas;
    private javax.swing.JSpinner jSpinner_cant_cambios;
    private javax.swing.JTextField jTextField_boDisponible;
    // End of variables declaration//GEN-END:variables

    ArrayList<DatosCombate> combatientes = new ArrayList<DatosCombate>();
    Principal principal;

    private void guardarArma() {
        int val = (Integer) jSpinner_cant_cambios.getValue();
        jSpinner_cant_cambios.setValue(val + 1);
        modificarBO();
    }

    private void equiparArma() {
        int val = (Integer) jSpinner_cant_cambios.getValue();
        jSpinner_cant_cambios.setValue(val + 1);
        modificarBO();
    }

    private void iniciarAtaques() {
        ArrayList<JPanelFormToken_Accion> enemigos = new ArrayList<>();
        DefaultListModel jdlm = (DefaultListModel) jList_blancos.getModel();
        
        for (Integer i : jList_blancos.getSelectedIndices()) {
            enemigos.add((JPanelFormToken_Accion) jdlm.get(i));
        }
        jdlm = (DefaultListModel) jList_combatientes.getModel();       
        
        JPanelFormToken_Accion jpa = (JPanelFormToken_Accion) jdlm.get(jList_combatientes.getSelectedIndex());
        jdlm = (DefaultListModel) jList_armas.getModel();       
        Arma arma = (Arma) jdlm.get(jList_armas.getSelectedIndex());
        
        ResolverAtaques ra = new ResolverAtaques(principal, true, jpa, enemigos, Integer.parseInt(jTextField_boDisponible.getText()),arma);
        ra.setVisible(true);
    }

    private void activarAtaqueButton() {
        boolean act = false;
        act = (!jList_blancos.isSelectionEmpty() && !jList_armas.isSelectionEmpty());
        jButton_atacar.setEnabled(act);
    }

}
