/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superrolbattle.ventanas;

import instancias.Accion;
import instancias.CampoDeBatalla;
import instancias.Token;
import instancias.properties.Arma;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import recursos.Recursos;
import superrolbattle.principal;

/**
 *
 * @author Juan
 */
public class DeclararAtaques extends javax.swing.JDialog {

    /**
     * Creates new form DeclararAtaques
     */
    public DeclararAtaques(java.awt.Frame parent, boolean modal, Token soldado) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.soldado = soldado;
        acc = CampoDeBatalla.getAccionesDeToken(soldado);
        enemigos = CampoDeBatalla.getAtacantesDeToken(soldado);

        this.jComboBoxEnemigos.setModel(new DefaultComboBoxModel(listadeEnemigosPosibles().toArray()));

        if (enemigos.size() > 0) {
            DefaultListModel modelo = new DefaultListModel();
            jList_atacantes.setModel(modelo);
            //(DefaultListModel) jList_atacantes.getModel();
            modelo.removeAllElements();
            for (Token enemigo : enemigos) {
                modelo.addElement(enemigo);
            }
            jList_atacantes.setModel(modelo);
            if (acc == null) {
                DefaultComboBoxModel dcb = (DefaultComboBoxModel) jComboBoxEnemigos.getModel();
                jComboBoxEnemigos.setSelectedItem(enemigos.get(0));
            }
        }

        instancias.properties.Arma[] armas = new Arma[]{soldado.getManoDER().getArmaEquipada(), soldado.getManoIZQ().getArmaEquipada()};
        this.jComboBoxArmas.setModel(new DefaultComboBoxModel(armas));

        if (acc != null) {
            DefaultComboBoxModel dcb = (DefaultComboBoxModel) jComboBoxEnemigos.getModel();
            //int sel = dcb.getIndexOf(acc.getDestino());
            jComboBoxEnemigos.setSelectedItem(acc.getDestino());
            //jComboBoxEnemigos.setModel(dcb);
        }

        int porc = soldado.definirPorcTactica();
        jSpinner_porcAtaque.setValue(porc);
        controlDistancia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxEnemigos = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxArmas = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton_brazoD = new javax.swing.JRadioButton();
        jRadioButton_brazoI = new javax.swing.JRadioButton();
        jPanel_distancia = new javax.swing.JPanel();
        jLabel_distancia = new javax.swing.JLabel();
        jSpinner_distancia = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner_porcAtaque = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_atacantes = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setMaximumSize(new java.awt.Dimension(224, 185));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel2.setText("Enemigo");
        jPanel3.add(jLabel2);

        jComboBoxEnemigos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBoxEnemigos);

        jLabel1.setText("Arma");
        jPanel3.add(jLabel1);

        jComboBoxArmas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxArmas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxArmasItemStateChanged(evt);
            }
        });
        jPanel3.add(jComboBoxArmas);

        jPanel6.setMaximumSize(new java.awt.Dimension(201, 38));
        jPanel6.setPreferredSize(new java.awt.Dimension(201, 38));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        buttonGroup1.add(jRadioButton_brazoD);
        jRadioButton_brazoD.setSelected(true);
        jRadioButton_brazoD.setText("Brazo D");
        jPanel6.add(jRadioButton_brazoD);

        buttonGroup1.add(jRadioButton_brazoI);
        jRadioButton_brazoI.setText("Brazo I (-30)");
        jPanel6.add(jRadioButton_brazoI);

        jPanel3.add(jPanel6);

        jPanel_distancia.setLayout(new javax.swing.BoxLayout(jPanel_distancia, javax.swing.BoxLayout.LINE_AXIS));

        jLabel_distancia.setText("  Distancia  ");
        jPanel_distancia.add(jLabel_distancia);

        jSpinner_distancia.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(3), Integer.valueOf(3), null, Integer.valueOf(3)));
        jPanel_distancia.add(jSpinner_distancia);

        jTextField1.setEditable(false);
        jTextField1.setText("mts.");
        jTextField1.setMaximumSize(new java.awt.Dimension(26, 28));
        jTextField1.setMinimumSize(new java.awt.Dimension(26, 28));
        jTextField1.setName(""); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(26, 28));
        jTextField1.setRequestFocusEnabled(false);
        jPanel_distancia.add(jTextField1);

        jPanel3.add(jPanel_distancia);

        jPanel7.setPreferredSize(new java.awt.Dimension(201, 20));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("% de bo para el Ataque");
        jPanel7.add(jLabel3);

        jSpinner_porcAtaque.setModel(new javax.swing.SpinnerNumberModel(100, 0, 100, 5));
        jPanel7.add(jSpinner_porcAtaque);

        jPanel3.add(jPanel7);

        jPanel5.add(jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel4.setText("Enemigos actuales");
        jPanel2.add(jLabel4);

        jList_atacantes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_atacantesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList_atacantes);

        jPanel2.add(jScrollPane1);

        jPanel5.add(jPanel2);

        jPanel1.add(jPanel5);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setMaximumSize(new java.awt.Dimension(351, 27));
        jPanel4.setPreferredSize(new java.awt.Dimension(351, 49));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel8.setMaximumSize(new java.awt.Dimension(149, 20));
        jPanel8.setMinimumSize(new java.awt.Dimension(149, 20));
        jPanel8.setPreferredSize(new java.awt.Dimension(149, 20));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8);

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList_atacantesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_atacantesValueChanged

    }//GEN-LAST:event_jList_atacantesValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Accion acc = new Accion();
        Arma arm = (Arma) jComboBoxArmas.getSelectedItem();
        int bono = 0;
        int porc = (int) jSpinner_porcAtaque.getValue();
        int tipoAccion = 0;
        if (arm.getClase() == Arma.CLASE_ARCO_CORTO || arm.getClase() == Arma.CLASE_ARCO_LARGO) {
            tipoAccion = Accion.TIPO_COMBATE_ARCO;
            bono = bonoSegunDistancia();
        } else if (arm.isdosManos()) {
            tipoAccion = Accion.TIPO_COMBATE_2_ARMAS;

        } else if (arm.getClase() == Arma.CLASE_MANO_DESNUDA) {
            tipoAccion = Accion.TIPO_COMBATE_PUÑO;
            bono = (jRadioButton_brazoI.isSelected()) ? -30 : 0;
        } else {
            tipoAccion = Accion.TIPO_COMBATE_1_ARMA;
            bono = (jRadioButton_brazoI.isSelected()) ? -30 : 0;
        }

        acc.setTipo(tipoAccion);
        acc.setDestino((Token) jComboBoxEnemigos.getSelectedItem());
        acc.setEmisor(soldado);
        soldado.setPorcentajeAtque(porc);

        acc.setMedio(new Object[]{jComboBoxArmas.getSelectedItem(), bono});

        CampoDeBatalla.agregarAccion(acc);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBoxArmasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxArmasItemStateChanged
        controlDistancia();
    }//GEN-LAST:event_jComboBoxArmasItemStateChanged

    /**
     * @param args the command line arguments
     */
    private ArrayList<Token> listadeEnemigosPosibles() {
        ArrayList<Token> enemigos = new ArrayList<Token>();
        enemigos.add(Token.nadie());

        for (Token enemigo : Recursos.soldados) {
            boolean mismoLado = enemigo.isLadoIzquierdo() == soldado.isLadoIzquierdo();

            if (!enemigo.equals(soldado) && (principal.dosLados || !mismoLado)) {
                enemigos.add(enemigo);
            }

        }
        return enemigos;
    }

    private void controlDistancia() {
        Arma arm = (Arma) jComboBoxArmas.getSelectedItem();
        if (arm.getClase() == Arma.CLASE_ARCO_CORTO || arm.getClase() == Arma.CLASE_ARCO_LARGO) {
            jPanel_distancia.setVisible(true);
        } else {
            jPanel_distancia.setVisible(false);
        }
        this.repaint();
    }

    private int bonoSegunDistancia() {
        int dist = (Integer) jSpinner_distancia.getValue();
        int bono = 0;
        Arma arm = (Arma) jComboBoxArmas.getSelectedItem();
        if (arm.getClase() == Arma.CLASE_ARCO_CORTO) {
            if (dist <= 3) {
                bono = 10;
            } else if (dist >= 30 && dist <= 40) {
                bono = -40;
            } else if (dist >= 40 && dist <= 50) {
                bono = -70;
            } else if (dist >= 51) {
                bono = -100;
            }
        } else if (arm.getClase() == Arma.CLASE_ARCO_LARGO) {
            if (dist <= 3) {
                bono = 20;
            } else if (dist >= 30 && dist <= 44) {
                bono = -30;
            } else if (dist >= 45 && dist <= 60) {
                bono = -45;
            } else if (dist >= 61 && dist <= 119) {
                bono = -60;
            } else if (dist >= 120) {
                bono = -60;
            }

        }
        return bono;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBoxArmas;
    private javax.swing.JComboBox jComboBoxEnemigos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_distancia;
    private javax.swing.JList jList_atacantes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel_distancia;
    private javax.swing.JRadioButton jRadioButton_brazoD;
    private javax.swing.JRadioButton jRadioButton_brazoI;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_distancia;
    private javax.swing.JSpinner jSpinner_porcAtaque;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private Token soldado;
    private Accion acc;
    private ArrayList<Token> enemigos;
}
