/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superrolbattle.ventanas;

import instancias.ListaDeSortilegios;
import java.util.ArrayList;
import java.util.SortedSet;
import java.util.TreeSet;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import superrolbattle.Principal;

/**
 *
 * @author TiranoJuan
 */
public class ElejirListaSortilegio extends javax.swing.JDialog {

    /**
     * Creates new form CrearListaSortilegio
     */
    public ElejirListaSortilegio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        SortedSet<String> profesiones = new TreeSet<String>();
        profesiones.add("-");
        for (ListaDeSortilegios lds : Principal.getTodasLasListasDeSortilegios()) {
            if (lds.getProfesion() != null) {
                profesiones.add(lds.getProfesion());
            }
        }
        jComboBox_profesion.setModel(new DefaultComboBoxModel(profesiones.toArray()));
        mostrarListas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jComboBox_dominio = new javax.swing.JComboBox<>();
        jComboBox_tipo_lista_sortilegio = new javax.swing.JComboBox<>();
        jComboBox_profesion = new javax.swing.JComboBox<>();
        jComboBox_listas = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton_aprender = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Lista de Sortilegios");
        setMaximumSize(new java.awt.Dimension(304, 173));
        setMinimumSize(new java.awt.Dimension(304, 173));
        setPreferredSize(new java.awt.Dimension(304, 173));

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 35, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        jComboBox_dominio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dominio Canalizacion", "Dominio Escencia", "Dominion Mentalismo" }));
        jComboBox_dominio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_dominioItemStateChanged(evt);
            }
        });
        jPanel2.add(jComboBox_dominio);

        jComboBox_tipo_lista_sortilegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista Abierta", "Lista Cerrada", "LIsta Cerrada de Profesion" }));
        jComboBox_tipo_lista_sortilegio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_tipo_lista_sortilegioItemStateChanged(evt);
            }
        });
        jPanel2.add(jComboBox_tipo_lista_sortilegio);

        jComboBox_profesion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista Abierta", "Lista Cerrada", "Lista Cerrada de Profesion" }));
        jComboBox_profesion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_profesionItemStateChanged(evt);
            }
        });
        jPanel2.add(jComboBox_profesion);

        jComboBox_listas.setMinimumSize(new java.awt.Dimension(224, 20));
        jComboBox_listas.setName(""); // NOI18N
        jComboBox_listas.setPreferredSize(new java.awt.Dimension(224, 20));
        jPanel2.add(jComboBox_listas);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton_aprender.setText("Aprender");
        jButton_aprender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aprenderActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_aprender);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_aprenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aprenderActionPerformed
        seleccionarLista();
    }//GEN-LAST:event_jButton_aprenderActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox_tipo_lista_sortilegioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_tipo_lista_sortilegioItemStateChanged
        mostrarListas();
    }//GEN-LAST:event_jComboBox_tipo_lista_sortilegioItemStateChanged

    private void jComboBox_dominioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_dominioItemStateChanged
        mostrarListas();
    }//GEN-LAST:event_jComboBox_dominioItemStateChanged

    private void jComboBox_profesionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_profesionItemStateChanged
        mostrarListas();
    }//GEN-LAST:event_jComboBox_profesionItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_aprender;
    private javax.swing.JComboBox<String> jComboBox_dominio;
    private javax.swing.JComboBox<String> jComboBox_listas;
    private javax.swing.JComboBox<String> jComboBox_profesion;
    private javax.swing.JComboBox<String> jComboBox_tipo_lista_sortilegio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public static ListaDeSortilegios lds;

    public static ListaDeSortilegios NuevaListaDeSortilegios(java.awt.Frame parent, boolean modal) {
        lds = null;
        ElejirListaSortilegio clds = new ElejirListaSortilegio(parent, modal);
        clds.setLocationRelativeTo(null);
        clds.setVisible(true);
        return lds;
    }
//
//    private void crearLista() {
//        lds = new ListaDeSortilegios();
//        lds.setNombre(jTextField_nombre_lds.getText());
//        lds.setDominio(jComboBox_dominio.getSelectedIndex());
//        lds.setTipo_lista(jComboBox_tipo_lista_sortilegio.getSelectedIndex());
//        if (jComboBox_tipo_lista_sortilegio.getSelectedIndex() == ListaDeSortilegios.TIPO_LISTA_CERRADA_PROFESION){
//            lds.setProfesion(jTextField_profesion_lds.getText());
//        }
//        this.dispose();
//    }
//    

    private void mostrarListas() {

        int filtro_dom = jComboBox_dominio.getSelectedIndex();
        int filtro_tipo = jComboBox_tipo_lista_sortilegio.getSelectedIndex();
        String filtro_profesion = jComboBox_profesion.getSelectedItem().toString();
        ArrayList<ListaDeSortilegios> a_lds = new ArrayList();
        for (ListaDeSortilegios lds : Principal.getTodasLasListasDeSortilegios()) {
            if (lds.getTipo_lista() == filtro_tipo && filtro_dom == lds.getDominio()) {
                if (filtro_tipo == ListaDeSortilegios.TIPO_LISTA_BASICA_PROFESION && lds.getProfesion().equals(filtro_profesion)) {
                    a_lds.add(lds);
                } else if (filtro_tipo != ListaDeSortilegios.TIPO_LISTA_BASICA_PROFESION) {
                    a_lds.add(lds);
                }
            }
        }
        jComboBox_listas.setModel(new DefaultComboBoxModel(a_lds.toArray()));

    }

    private void seleccionarLista() {
        if (jComboBox_listas.getSelectedIndex() > -1) {
            lds = (ListaDeSortilegios) jComboBox_listas.getSelectedItem();
            this.dispose();
        }
    }

}
