/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superrolbattle.ventanas;

import instancias.Sortilegio;
import instancias.Token;
import javax.swing.DefaultComboBoxModel;
import superrolbattle.Principal;

/**
 *
 * @author TiranoJuan
 */
public class NuevoSortilegio extends javax.swing.JDialog {

    /**
     * Creates new form NuevoSortilegio
     */
    public NuevoSortilegio(java.awt.Frame parent, boolean modal, Token token) {
        super(parent, modal);
        initComponents();
        this.token = token;
        jComboBox_todosLosSortilegios.setModel(new DefaultComboBoxModel(Principal.getTodosLosSortilegios().toArray()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox_todosLosSortilegios = new javax.swing.JComboBox<>();
        jButton_copiar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner_lv = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_dominio = new javax.swing.JComboBox<>();
        jCheckBox_consume = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField_alcance = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_desc = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jButton_guardar_sortilegio = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Copiar de"));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jComboBox_todosLosSortilegios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox_todosLosSortilegios);

        jButton_copiar.setText("Copiar");
        jButton_copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_copiarActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_copiar);

        jButton1.setText("Aprender");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jPanel5.add(jPanel4);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);

        jTextField_Nombre.setMinimumSize(new java.awt.Dimension(6, 130));
        jTextField_Nombre.setPreferredSize(new java.awt.Dimension(330, 20));
        jPanel1.add(jTextField_Nombre);

        jPanel7.add(jPanel1);

        jLabel2.setText("Lv");
        jPanel2.add(jLabel2);

        jSpinner_lv.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));
        jPanel2.add(jSpinner_lv);

        jLabel4.setText("Dominio");
        jPanel2.add(jLabel4);

        jComboBox_dominio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Canalizacion", "Escencia", "Mentalismo" }));
        jPanel2.add(jComboBox_dominio);

        jCheckBox_consume.setText("Consume PP");
        jPanel2.add(jCheckBox_consume);

        jLabel6.setText("Alcance");
        jPanel2.add(jLabel6);

        jTextField_alcance.setText(" ");
        jTextField_alcance.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel2.add(jTextField_alcance);

        jPanel7.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion"));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jTextArea_desc.setColumns(20);
        jTextArea_desc.setRows(5);
        jScrollPane1.setViewportView(jTextArea_desc);

        jPanel3.add(jScrollPane1);

        jPanel7.add(jPanel3);

        jPanel5.add(jPanel7);

        getContentPane().add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton_guardar_sortilegio.setText("Guardar Nuevo");
        jButton_guardar_sortilegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardar_sortilegioActionPerformed(evt);
            }
        });
        jPanel6.add(jButton_guardar_sortilegio);

        jButton_cancelar.setText("Cancelar");
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });
        jPanel6.add(jButton_cancelar);

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_copiarActionPerformed
        copiarSortilegio();
    }//GEN-LAST:event_jButton_copiarActionPerformed

    private void jButton_guardar_sortilegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardar_sortilegioActionPerformed
        Sortilegio s = new Sortilegio();
        s.setNombre(jTextField_Nombre.getText());
        s.setLv((Integer) jSpinner_lv.getValue());
        //s.setDuracion(jt);
        s.setDominio(jComboBox_dominio.getSelectedIndex());
        s.setAlcance(jTextField_alcance.getText());
        s.setDescp(jTextArea_desc.getText());
        s.setConsumePP(jCheckBox_consume.isSelected());

        int ind_ns = Principal.crearSortilegioNuevo(s);
        token.aprenderSortilegio(ind_ns);
        this.dispose();
    }//GEN-LAST:event_jButton_guardar_sortilegioActionPerformed

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_cancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int s = jComboBox_todosLosSortilegios.getSelectedIndex();
        if (!token.conoceSortilegio(s)) {
            token.aprenderSortilegio(s);
            this.dispose();
        } else
            recursos.Recursos.informar(token.getNombre() + " ya conoce este Sortilegio");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void copiarSortilegio() {
        Sortilegio s = (Sortilegio) jComboBox_todosLosSortilegios.getSelectedItem();
        jTextArea_desc.setText(s.getDescp());
        jTextField_Nombre.setText(s.getNombre());
        jCheckBox_consume.setSelected(s.isConsumePP());
        jComboBox_dominio.setSelectedIndex(s.getDominio());
        jSpinner_lv.setValue(s.getLv());
        jTextField_alcance.setText(s.getAlcance());

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JButton jButton_copiar;
    private javax.swing.JButton jButton_guardar_sortilegio;
    private javax.swing.JCheckBox jCheckBox_consume;
    private javax.swing.JComboBox<String> jComboBox_dominio;
    private javax.swing.JComboBox<String> jComboBox_todosLosSortilegios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_lv;
    private javax.swing.JTextArea jTextArea_desc;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_alcance;
    // End of variables declaration//GEN-END:variables
    private Token token;

}
